-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["파우아 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "마나 재생 속도 (20-30)% 증가",
	implicitModTypes = { { "resource", "mana" }, },
	req = { },
}
itemBases["산호 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "1초마다 생명력 (2-4) 재생",
	implicitModTypes = { { "flat_life_regen", "resource", "life" }, },
	req = { },
}
itemBases["호박 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "힘 +(20-30)",
	implicitModTypes = { { "attribute" }, },
	req = { level = 5, },
}
itemBases["비취 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "민첩 +(20-30)",
	implicitModTypes = { { "attribute" }, },
	req = { level = 5, },
}
itemBases["청금석 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "지능 +(20-30)",
	implicitModTypes = { { "attribute" }, },
	req = { level = 5, },
}
itemBases["황금 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "발견하는 아이템 희귀도 (12-20)% 증가",
	implicitModTypes = { {  }, },
	req = { level = 8, },
}
itemBases["오닉스 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "모든 능력치 +(10-16)",
	implicitModTypes = { { "attribute" }, },
	req = { level = 20, },
}
itemBases["터키석 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "민첩 및 지능 +(16-24)",
	implicitModTypes = { { "attribute" }, },
	req = { level = 16, },
}
itemBases["마노 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "힘 및 지능 +(16-24)",
	implicitModTypes = { { "attribute" }, },
	req = { level = 16, },
}
itemBases["황수정 목걸이"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "힘 및 민첩 +(16-24)",
	implicitModTypes = { { "attribute" }, },
	req = { level = 16, },
}
itemBases["루비 목걸이"] = {
	type = "Amulet",
	tags = { not_for_sale = true, default = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "화염 저항 +(20-30)%",
	implicitModTypes = { { "elemental", "fire", "resistance" }, },
	req = { },
}
itemBases["무보석 목걸이"] = {
	type = "Amulet",
	tags = { not_for_sale = true, default = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "홈 1개",
	implicitModTypes = { {  }, },
	req = { level = 5, },
}
itemBases["파란 진주 목걸이"] = {
	type = "Amulet",
	tags = { amuletatlas1 = true, not_for_sale = true, atlas_base_type = true, amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "마나 재생 속도 (48-56)% 증가",
	implicitModTypes = { { "resource", "mana" }, },
	req = { level = 77, },
}
itemBases["대리석 목걸이"] = {
	type = "Amulet",
	tags = { amuletatlas2 = true, not_for_sale = true, atlas_base_type = true, amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "1초마다 생명력의 (1.2-1.6)% 재생",
	implicitModTypes = { { "resource", "life" }, },
	req = { level = 74, },
}
itemBases["바다유리 목걸이"] = {
	type = "Amulet",
	tags = { not_for_sale = true, atlas_base_type = true, amuletatlas3 = true, amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "에너지 보호막 재충전 시작 속도 (10-15)% 가속",
	implicitModTypes = { { "energy_shield", "defences" }, },
	req = { level = 74, },
}
itemBases["관측기 목걸이"] = {
	type = "Amulet",
	tags = { not_for_sale = true, experimental_base = true, default = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "고정 속성 변경 불가\n엘더, 쉐이퍼, 모든 정복자 영향력 보유",
	implicitModTypes = { {  }, {  }, },
	req = { level = 69, },
}
itemBases["평범한 목걸이"] = {
	type = "Amulet",
	tags = { not_for_sale = true, experimental_base = true, default = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "접두어 속성 부여의 최대 개수 -1개\n접미어 속성 부여의 최대 개수 -1개\n고정 속성 변경 불가\n무작위 속성 부여 규모 25% 증가",
	implicitModTypes = { {  }, {  }, {  }, {  }, },
	req = { level = 24, },
}
itemBases["흑옥 목걸이"] = {
	type = "Amulet",
	hidden = true,
	tags = { demigods = true, not_for_sale = true, default = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "모든 원소 저항 +(8-12)%",
	implicitModTypes = { { "elemental", "resistance" }, },
	req = { level = 12, },
}

itemBases["검은 턱 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "홈 1개",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["뼈 첨탑 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "최대 마나 (20-30)% 증가",
	implicitModTypes = { { "resource", "mana" }, },
	req = { },
}
itemBases["재비늘 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "화염 피해 (20-30)% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "fire" }, },
	req = { },
}
itemBases["외가지뿔 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "번개 피해 (20-30)% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "lightning" }, },
	req = { },
}
itemBases["심해의 존재 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "냉기 피해 (20-30)% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "cold" }, },
	req = { },
}
itemBases["골절늑골 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "일반 물리 피해 (20-30)% 증가",
	implicitModTypes = { { "physical_damage", "damage", "physical" }, },
	req = { },
}
itemBases["죽은 손 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "카오스 피해 (19-31)% 증가",
	implicitModTypes = { { "chaos_damage", "damage", "chaos" }, },
	req = { },
}
itemBases["산 송장 살점 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "소환 가능한 좀비 최대치 +1",
	implicitModTypes = { { "minion" }, },
	req = { },
}
itemBases["썩은 머리 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "물고기 이빨 민감도 (30-40)% 증가",
	implicitModTypes = { { "green_herring" }, },
	req = { },
}
itemBases["아래턱 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "공격 및 시전 속도 (6-10)% 증가",
	implicitModTypes = { { "attack", "caster", "speed" }, },
	req = { },
}
itemBases["번데기 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "주문 피해 (20-30)% 증가",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	req = { },
}
itemBases["꿈틀거리는 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "공격 피해 (20-30)% 증가",
	implicitModTypes = { { "damage", "attack" }, },
	req = { },
}
itemBases["사술발톱 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "일반 치명타 확률 (40-50)% 증가",
	implicitModTypes = { { "critical" }, },
	req = { },
}
itemBases["원시 해골 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "1초마다 생명력의 2% 재생",
	implicitModTypes = { { "resource", "life" }, },
	req = { },
}
itemBases["변신자발톱 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "일반 치명타 피해 배율 +(24-36)%",
	implicitModTypes = { { "damage", "critical" }, },
	req = { },
}
itemBases["분할도롱뇽 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "(4-6)%의 확률로 동결, 감전 및 점화 유발",
	implicitModTypes = { { "elemental", "fire", "cold", "lightning", "ailment" }, },
	req = { },
}
itemBases["움켜잡는 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "일반 방어력 (15-25)% 증가",
	implicitModTypes = { { "defences" }, },
	req = { },
}
itemBases["쌍둥이 새 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 화염 피해의 50%를 냉기 피해로 받음",
	implicitModTypes = { { "elemental", "fire", "cold" }, },
	req = { },
}
itemBases["쌍둥이 새 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 화염 피해의 50%를 번개 피해로 받음",
	implicitModTypes = { { "elemental", "fire", "lightning" }, },
	req = { },
}
itemBases["쌍둥이 새 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 냉기 피해의 50%를 화염 피해로 받음",
	implicitModTypes = { { "elemental", "fire", "cold" }, },
	req = { },
}
itemBases["쌍둥이 새 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 냉기 피해의 50%를 번개 피해로 받음",
	implicitModTypes = { { "elemental", "cold", "lightning" }, },
	req = { },
}
itemBases["쌍둥이 새 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 번개 피해의 50%를 냉기 피해로 받음",
	implicitModTypes = { { "elemental", "cold", "lightning" }, },
	req = { },
}
itemBases["쌍둥이 새 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 번개 피해의 50%를 화염 피해로 받음",
	implicitModTypes = { { "elemental", "fire", "lightning" }, },
	req = { },
}
itemBases["송곳니턱 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "최대 생명력 (8-12)% 증가",
	implicitModTypes = { { "resource", "life" }, },
	req = { },
}
itemBases["뿔 달린 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "투사체가 대상 2개를 추가 관통",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["척추융합 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "발견하는 아이템 수량 (6-10)% 증가",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["세 마리 쥐 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "능력치 (12-16)% 증가",
	implicitModTypes = { { "attribute" }, },
	req = { },
}
itemBases["쌍둥이 원숭이 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "효과 범위 (5-8)% 증가",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["긴 이빨 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "받는 물리 피해 (4-6)% 추가 감소",
	implicitModTypes = { { "physical" }, },
	req = { },
}
itemBases["썩은 깃털 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피해 (25-35)% 증가",
	implicitModTypes = { { "damage" }, },
	req = { },
}
itemBases["원숭이 발 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "처치 시 10%의 확률로 권능 충전 획득",
	implicitModTypes = { { "power_charge" }, },
	req = { },
}
itemBases["원숭이 발 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "처치 시 10%의 확률로 격분 충전 획득",
	implicitModTypes = { { "frenzy_charge" }, },
	req = { },
}
itemBases["원숭이 발 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "처치 시 10%의 확률로 인내 충전 획득",
	implicitModTypes = { { "endurance_charge" }, },
	req = { },
}
itemBases["세 개의 손 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "물리 피해의 (6-12)%를 무작위 원소 피해로 추가",
	implicitModTypes = { { "physical_damage", "elemental_damage", "damage", "physical", "elemental" }, },
	req = { },
}
itemBases["위대한 늑대 부적"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { amulet = true, default = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicitModTypes = { },
	req = { },
}
itemBases["Avian Twins Talisman (Fire-To-Cold)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 화염 피해의 50%를 냉기 피해로 받음",
	implicitModTypes = { { "elemental", "fire", "cold" }, },
	req = { },
}
itemBases["Avian Twins Talisman (Fire-To-Lightning)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 화염 피해의 50%를 번개 피해로 받음",
	implicitModTypes = { { "elemental", "fire", "lightning" }, },
	req = { },
}
itemBases["Avian Twins Talisman (Cold-To-Lightning)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 냉기 피해의 50%를 화염 피해로 받음",
	implicitModTypes = { { "elemental", "fire", "cold" }, },
	req = { },
}
itemBases["Avian Twins Talisman (Cold-To-Fire)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 냉기 피해의 50%를 번개 피해로 받음",
	implicitModTypes = { { "elemental", "cold", "lightning" }, },
	req = { },
}
itemBases["Avian Twins Talisman (Lightning-To-Cold)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "피격 시 번개 피해의 50%를 냉기 피해로 받음",
	implicitModTypes = { { "elemental", "cold", "lightning" }, },
	req = { },
}
itemBases["Monkey Paw Talisman (Power)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "처치 시 10%의 확률로 권능 충전 획득",
	implicitModTypes = { { "power_charge" }, },
	req = { },
}
itemBases["Monkey Paw Talisman (Frenzy)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	influenceTags = { shaper = "amulet_shaper", elder = "amulet_elder", adjudicator = "amulet_adjudicator", basilisk = "amulet_basilisk", crusader = "amulet_crusader", eyrie = "amulet_eyrie", cleansing = "amulet_cleansing", tangle = "amulet_tangle" },
	implicit = "처치 시 10%의 확률로 격분 충전 획득",
	implicitModTypes = { { "frenzy_charge" }, },
	req = { },
}
