-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["녹슨 손도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 6, PhysicalMax = 11, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { str = 12, dex = 6, },
}
itemBases["비취 손도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 10, PhysicalMax = 15, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { level = 6, str = 21, dex = 10, },
}
itemBases["선상 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 11, PhysicalMax = 21, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 11, str = 28, dex = 19, },
}
itemBases["가로날도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 12, PhysicalMax = 35, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 16, str = 48, dex = 14, },
}
itemBases["넓은날 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 19, PhysicalMax = 34, CritChanceBase = 5, AttackRateBase = 1.35, Range = 11, },
	req = { level = 21, str = 54, dex = 25, },
}
itemBases["전투용 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 14, PhysicalMax = 42, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 25, str = 58, dex = 33, },
}
itemBases["장식된 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 27, PhysicalMax = 50, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 29, str = 80, dex = 23, },
}
itemBases["영체 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 29, PhysicalMax = 48, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 33, str = 85, dex = 37, },
}
itemBases["조각된 손도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, not_for_sale = true, maraketh = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicit = "일반 물리 피해 8% 증가",
	implicitModTypes = { { "physical_damage", "damage", "physical" }, },
	weapon = { PhysicalMin = 26, PhysicalMax = 46, CritChanceBase = 5, AttackRateBase = 1.35, Range = 11, },
	req = { level = 35, str = 93, dex = 43, },
}
itemBases["벽옥 손도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 32, PhysicalMax = 50, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 36, str = 86, dex = 40, },
}
itemBases["토마호크"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 25, PhysicalMax = 46, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 39, str = 81, dex = 56, },
}
itemBases["팔목 절단기"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 26, PhysicalMax = 79, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 42, str = 112, dex = 32, },
}
itemBases["전쟁용 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 35, PhysicalMax = 65, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 45, str = 106, dex = 49, },
}
itemBases["가르기용 스플리터"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 24, PhysicalMax = 71, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 48, str = 105, dex = 60, },
}
itemBases["의식용 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 45, PhysicalMax = 83, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 51, str = 134, dex = 39, },
}
itemBases["악령 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 45, PhysicalMax = 75, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 54, str = 134, dex = 59, },
}
itemBases["아로새긴 손도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, not_for_sale = true, maraketh = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicit = "일반 물리 피해 8% 증가",
	implicitModTypes = { { "physical_damage", "damage", "physical" }, },
	weapon = { PhysicalMin = 40, PhysicalMax = 71, CritChanceBase = 5, AttackRateBase = 1.35, Range = 11, },
	req = { level = 56, str = 143, dex = 66, },
}
itemBases["카루이 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 49, PhysicalMax = 77, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 57, str = 132, dex = 62, },
}
itemBases["공성용 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 38, PhysicalMax = 70, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 59, str = 119, dex = 82, },
}
itemBases["강탈자 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 38, PhysicalMax = 114, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 61, str = 167, dex = 57, },
}
itemBases["도살자 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, top_tier_base_item_type = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 47, PhysicalMax = 87, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 63, str = 149, dex = 76, },
}
itemBases["바알 손도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, top_tier_base_item_type = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 30, PhysicalMax = 90, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 65, str = 140, dex = 86, },
}
itemBases["왕실 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, top_tier_base_item_type = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 54, PhysicalMax = 100, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 67, str = 167, dex = 57, },
}
itemBases["지옥불 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, top_tier_base_item_type = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 51, PhysicalMax = 85, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 69, str = 158, dex = 76, },
}
itemBases["룬 손도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, not_for_sale = true, maraketh = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicit = "일반 물리 피해 12% 증가",
	implicitModTypes = { { "physical_damage", "damage", "physical" }, },
	weapon = { PhysicalMin = 44, PhysicalMax = 79, CritChanceBase = 5, AttackRateBase = 1.35, Range = 11, },
	req = { level = 71, str = 163, dex = 82, },
}
itemBases["가학의 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, not_for_sale = true, weapon = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicit = "격노 최대치 +10",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 44, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 30, str = 78, dex = 34, },
}
itemBases["책망의 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, not_for_sale = true, weapon = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicit = "격노 최대치 +10",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 32, PhysicalMax = 67, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 50, str = 124, dex = 54, },
}
itemBases["광기의 도끼"] = {
	type = "One Handed Axe",
	socketLimit = 3,
	tags = { axe = true, onehand = true, not_for_sale = true, weapon = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "axe_shaper", elder = "axe_elder", adjudicator = "axe_adjudicator", basilisk = "axe_basilisk", crusader = "axe_crusader", eyrie = "axe_eyrie", cleansing = "axe_cleansing", tangle = "axe_tangle" },
	implicit = "격노 최대치 +10",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 38, PhysicalMax = 79, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 70, str = 163, dex = 84, },
}

itemBases["돌도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 12, PhysicalMax = 20, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { str = 17, dex = 8, },
}
itemBases["비취 절단기"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 19, PhysicalMax = 30, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 9, str = 31, dex = 9, },
}
itemBases["벌목스플리터"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 19, PhysicalMax = 39, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 13, str = 36, dex = 17, },
}
itemBases["자루 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 29, PhysicalMax = 43, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 18, str = 44, dex = 25, },
}
itemBases["양날 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 36, PhysicalMax = 60, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 23, str = 62, dex = 27, },
}
itemBases["도금된 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 43, PhysicalMax = 58, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 28, str = 64, dex = 37, },
}
itemBases["그림자 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 49, PhysicalMax = 73, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 33, str = 80, dex = 37, },
}
itemBases["단검 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, maraketh = true, not_for_sale = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicit = "치명타 확률 50% 증가",
	implicitModTypes = { { "attack", "critical" }, },
	weapon = { PhysicalMin = 53, PhysicalMax = 83, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 36, str = 89, dex = 43, },
}
itemBases["벽옥 절단기"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 58, PhysicalMax = 91, CritChanceBase = 5, AttackRateBase = 1.15, Range = 13, },
	req = { level = 37, str = 100, dex = 29, },
}
itemBases["목재용 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 48, PhysicalMax = 99, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 41, str = 97, dex = 45, },
}
itemBases["참수자 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 61, PhysicalMax = 92, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 45, str = 99, dex = 57, },
}
itemBases["라브리스"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 74, PhysicalMax = 123, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 49, str = 122, dex = 53, },
}
itemBases["귀족 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 76, PhysicalMax = 103, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 52, str = 113, dex = 65, },
}
itemBases["심연의 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 81, PhysicalMax = 121, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 55, str = 128, dex = 60, },
}
itemBases["발톱 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, maraketh = true, not_for_sale = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicit = "치명타 확률 50% 증가",
	implicitModTypes = { { "attack", "critical" }, },
	weapon = { PhysicalMin = 88, PhysicalMax = 138, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 59, str = 140, dex = 67, },
}
itemBases["카루이 절단기"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 121, PhysicalMax = 189, CritChanceBase = 5, AttackRateBase = 1.05, Range = 13, },
	req = { level = 58, str = 151, dex = 43, },
}
itemBases["작렬하는 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicit = "출혈 지속 피해 배율 +20%",
	implicitModTypes = { { "physical_damage", "bleed", "damage", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 74, PhysicalMax = 155, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 60, str = 149, dex = 76, },
}
itemBases["에조미어 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, top_tier_base_item_type = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 87, PhysicalMax = 131, CritChanceBase = 5.7, AttackRateBase = 1.35, Range = 13, },
	req = { level = 62, str = 140, dex = 86, },
}
itemBases["바알 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, top_tier_base_item_type = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicit = "명중 시 25%의 확률로 힘줄 절단",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 104, PhysicalMax = 174, CritChanceBase = 5, AttackRateBase = 1.15, Range = 13, },
	req = { level = 64, str = 158, dex = 76, },
}
itemBases["절대군주 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, top_tier_base_item_type = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 90, PhysicalMax = 122, CritChanceBase = 5, AttackRateBase = 1.4, Range = 13, },
	req = { level = 66, str = 140, dex = 86, },
}
itemBases["공허의 도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, top_tier_base_item_type = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 96, PhysicalMax = 144, CritChanceBase = 6, AttackRateBase = 1.25, Range = 13, },
	req = { level = 68, str = 149, dex = 76, },
}
itemBases["살점 거열기"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, maraketh = true, not_for_sale = true, two_hand_weapon = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicit = "치명타 확률 50% 증가",
	implicitModTypes = { { "attack", "critical" }, },
	weapon = { PhysicalMin = 97, PhysicalMax = 152, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 70, str = 156, dex = 84, },
}
itemBases["최종형 가로날도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, weapon = true, not_for_sale = true, two_hand_weapon = true, experimental_base = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicit = "최대 퀄리티 +20%",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 36, PhysicalMax = 56, CritChanceBase = 5, AttackRateBase = 1.35, Range = 13, },
	req = { level = 30, },
}
itemBases["연마한 가로날도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, weapon = true, not_for_sale = true, two_hand_weapon = true, experimental_base = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicit = "최대 퀄리티 +20%",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 55, PhysicalMax = 86, CritChanceBase = 5, AttackRateBase = 1.35, Range = 13, },
	req = { level = 50, },
}
itemBases["정점의 가로날도끼"] = {
	type = "Two Handed Axe",
	socketLimit = 6,
	tags = { axe = true, weapon = true, not_for_sale = true, two_hand_weapon = true, experimental_base = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_axe_shaper", elder = "2h_axe_elder", adjudicator = "2h_axe_adjudicator", basilisk = "2h_axe_basilisk", crusader = "2h_axe_crusader", eyrie = "2h_axe_eyrie", cleansing = "2h_axe_cleansing", tangle = "2h_axe_tangle" },
	implicit = "최대 퀄리티 +20%",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 65, PhysicalMax = 101, CritChanceBase = 5, AttackRateBase = 1.35, Range = 13, },
	req = { level = 70, },
}
