-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["판금 조끼"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 19, ArmourBaseMax = 27, MovementPenalty = 3, },
	req = { str = 12, },
}
itemBases["가슴 보호 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 68, ArmourBaseMax = 89, MovementPenalty = 5, },
	req = { level = 6, str = 25, },
}
itemBases["구리 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 176, ArmourBaseMax = 221, MovementPenalty = 5, },
	req = { level = 17, str = 53, },
}
itemBases["전쟁용 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 216, ArmourBaseMax = 248, MovementPenalty = 5, },
	req = { level = 21, str = 63, },
}
itemBases["전신 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 284, ArmourBaseMax = 319, MovementPenalty = 5, },
	req = { level = 28, str = 81, },
}
itemBases["투기장 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 324, ArmourBaseMax = 389, MovementPenalty = 5, },
	req = { level = 32, str = 91, },
}
itemBases["위풍당당한 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 353, ArmourBaseMax = 417, MovementPenalty = 5, },
	req = { level = 35, str = 99, },
}
itemBases["청동 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 373, ArmourBaseMax = 429, MovementPenalty = 5, },
	req = { level = 37, str = 104, },
}
itemBases["전투용 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 412, ArmourBaseMax = 474, MovementPenalty = 5, },
	req = { level = 41, str = 114, },
}
itemBases["태양의 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 451, ArmourBaseMax = 506, MovementPenalty = 5, },
	req = { level = 45, str = 124, },
}
itemBases["원형 경기장 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 491, ArmourBaseMax = 589, MovementPenalty = 5, },
	req = { level = 49, str = 134, },
}
itemBases["압도적인 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 530, ArmourBaseMax = 625, MovementPenalty = 5, },
	req = { level = 53, str = 145, },
}
itemBases["황금 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 559, ArmourBaseMax = 643, MovementPenalty = 5, },
	req = { level = 56, str = 152, },
}
itemBases["십자군 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 601, ArmourBaseMax = 691, MovementPenalty = 5, },
	req = { level = 59, str = 160, },
}
itemBases["우주의 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, str_armour = true, armour = true, top_tier_base_item_type = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicit = "모든 원소 저항 +(8-12)%",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { ArmourBaseMin = 711, ArmourBaseMax = 782, MovementPenalty = 5, },
	req = { level = 62, str = 180, },
}
itemBases["검투사 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, str_armour = true, armour = true, top_tier_base_item_type = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 738, ArmourBaseMax = 848, MovementPenalty = 5, },
	req = { level = 65, str = 177, },
}
itemBases["영광의 판금 갑옷"] = {
	type = "Body Armour",
	subType = "Armour",
	socketLimit = 6,
	tags = { body_armour = true, str_armour = true, armour = true, top_tier_base_item_type = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 776, ArmourBaseMax = 892, },
	req = { level = 68, str = 191, },
}

itemBases["허름한 조끼"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 29, EvasionBaseMax = 41, MovementPenalty = 3, },
	req = { dex = 14, },
}
itemBases["끈을 멘 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 98, EvasionBaseMax = 127, MovementPenalty = 3, },
	req = { level = 9, dex = 32, },
}
itemBases["사슴가죽 튜닉"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 176, EvasionBaseMax = 221, MovementPenalty = 3, },
	req = { level = 17, dex = 53, },
}
itemBases["거친 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 255, EvasionBaseMax = 306, MovementPenalty = 3, },
	req = { level = 25, dex = 73, },
}
itemBases["전신 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 284, EvasionBaseMax = 327, MovementPenalty = 3, },
	req = { level = 28, dex = 81, },
}
itemBases["태양의 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 324, EvasionBaseMax = 382, MovementPenalty = 3, },
	req = { level = 32, dex = 91, },
}
itemBases["도둑의 의복"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 353, EvasionBaseMax = 396, MovementPenalty = 3, },
	req = { level = 35, dex = 99, },
}
itemBases["장어가죽 튜닉"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 373, EvasionBaseMax = 429, MovementPenalty = 3, },
	req = { level = 37, dex = 104, },
}
itemBases["개척자 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 412, EvasionBaseMax = 495, MovementPenalty = 3, },
	req = { level = 41, dex = 114, },
}
itemBases["영광의 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 451, EvasionBaseMax = 519, MovementPenalty = 3, },
	req = { level = 45, dex = 124, },
}
itemBases["광환의 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 491, EvasionBaseMax = 579, MovementPenalty = 3, },
	req = { level = 49, dex = 134, },
}
itemBases["살인자의 의복"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 530, EvasionBaseMax = 594, MovementPenalty = 3, },
	req = { level = 53, dex = 145, },
}
itemBases["상어가죽 튜닉"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 559, EvasionBaseMax = 643, MovementPenalty = 3, },
	req = { level = 56, dex = 152, },
}
itemBases["운명의 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 601, EvasionBaseMax = 721, MovementPenalty = 3, },
	req = { level = 59, dex = 160, },
}
itemBases["정교한 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, dex_armour = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 704, EvasionBaseMax = 810, MovementPenalty = 3, },
	req = { level = 62, dex = 170, },
}
itemBases["성좌의 가죽 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, dex_armour = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 854, EvasionBaseMax = 982, MovementPenalty = 3, },
	req = { level = 65, dex = 197, },
}
itemBases["암살자의 의복"] = {
	type = "Body Armour",
	subType = "Evasion",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, dex_armour = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicit = "이동 속도 3% 증가",
	implicitModTypes = { { "speed" }, },
	armour = { EvasionBaseMin = 737, EvasionBaseMax = 811, },
	req = { level = 68, dex = 183, },
}

itemBases["단순한 로브"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 14, EnergyShieldBaseMax = 20, MovementPenalty = 3, },
	req = { int = 17, },
}
itemBases["실크 조끼"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 30, EnergyShieldBaseMax = 38, MovementPenalty = 3, },
	req = { level = 11, int = 37, },
}
itemBases["학자의 로브"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 43, EnergyShieldBaseMax = 53, MovementPenalty = 3, },
	req = { level = 18, int = 55, },
}
itemBases["실크 의복"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 56, EnergyShieldBaseMax = 64, MovementPenalty = 3, },
	req = { level = 25, int = 73, },
}
itemBases["마법사의 법의"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 62, EnergyShieldBaseMax = 69, MovementPenalty = 3, },
	req = { level = 28, int = 81, },
}
itemBases["실크 로브"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 69, EnergyShieldBaseMax = 80, MovementPenalty = 3, },
	req = { level = 32, int = 91, },
}
itemBases["비법가 예복"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 75, EnergyShieldBaseMax = 88, MovementPenalty = 3, },
	req = { level = 35, int = 99, },
}
itemBases["현자의 로브"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 79, EnergyShieldBaseMax = 90, MovementPenalty = 3, },
	req = { level = 37, int = 104, },
}
itemBases["실크 외투"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 86, EnergyShieldBaseMax = 104, MovementPenalty = 3, },
	req = { level = 41, int = 114, },
}
itemBases["요술사의 법의"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 94, EnergyShieldBaseMax = 105, MovementPenalty = 3, },
	req = { level = 45, int = 124, },
}
itemBases["거미줄 실크 로브"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 101, EnergyShieldBaseMax = 117, MovementPenalty = 3, },
	req = { level = 49, int = 134, },
}
itemBases["파괴자 예복"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 109, EnergyShieldBaseMax = 129, MovementPenalty = 3, },
	req = { level = 53, int = 145, },
}
itemBases["석학의 로브"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 115, EnergyShieldBaseMax = 132, MovementPenalty = 3, },
	req = { level = 56, int = 152, },
}
itemBases["네크로맨서 실크 갑옷"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 123, EnergyShieldBaseMax = 147, MovementPenalty = 3, },
	req = { level = 59, int = 160, },
}
itemBases["오컬티스트의 법의"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, int_armour = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicit = "주문 피해 (3-10)% 증가",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { EnergyShieldBaseMin = 137, EnergyShieldBaseMax = 151, MovementPenalty = 3, },
	req = { level = 62, int = 180, },
}
itemBases["과부거미줄 실크 로브"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, int_armour = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 157, EnergyShieldBaseMax = 181, MovementPenalty = 3, },
	req = { level = 65, int = 187, },
}
itemBases["바알 예복"] = {
	type = "Body Armour",
	subType = "Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, int_armour = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 171, EnergyShieldBaseMax = 197, MovementPenalty = 3, },
	req = { level = 68, int = 194, },
}

itemBases["미늘 조끼"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 27, ArmourBaseMax = 38, EvasionBaseMin = 27, EvasionBaseMax = 38, MovementPenalty = 3, },
	req = { str = 10, dex = 10, },
}
itemBases["가벼운 브리간딘"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 48, ArmourBaseMax = 63, EvasionBaseMin = 48, EvasionBaseMax = 63, MovementPenalty = 3, },
	req = { level = 8, str = 16, dex = 16, },
}
itemBases["비늘 더블릿"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 97, ArmourBaseMax = 121, EvasionBaseMin = 97, EvasionBaseMax = 121, MovementPenalty = 3, },
	req = { level = 17, str = 28, dex = 28, },
}
itemBases["보병 브리간딘"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 119, ArmourBaseMax = 142, EvasionBaseMin = 119, EvasionBaseMax = 142, MovementPenalty = 3, },
	req = { level = 21, str = 34, dex = 34, },
}
itemBases["전신 미늘 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 156, ArmourBaseMax = 180, EvasionBaseMin = 156, EvasionBaseMax = 180, MovementPenalty = 3, },
	req = { level = 28, str = 43, dex = 43, },
}
itemBases["병사용 브리간딘"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 178, ArmourBaseMax = 210, EvasionBaseMin = 178, EvasionBaseMax = 210, MovementPenalty = 3, },
	req = { level = 32, str = 48, dex = 48, },
}
itemBases["야전 라멜라"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 194, ArmourBaseMax = 223, EvasionBaseMin = 194, EvasionBaseMax = 223, MovementPenalty = 3, },
	req = { level = 35, str = 53, dex = 53, },
}
itemBases["아룡 비늘 더블릿"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 210, ArmourBaseMax = 236, EvasionBaseMin = 210, EvasionBaseMax = 236, MovementPenalty = 3, },
	req = { level = 38, str = 57, dex = 57, },
}
itemBases["경기병 브리간딘"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 232, ArmourBaseMax = 278, EvasionBaseMin = 232, EvasionBaseMax = 278, MovementPenalty = 3, },
	req = { level = 42, str = 62, dex = 62, },
}
itemBases["전신 아룡 비늘 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 254, ArmourBaseMax = 292, EvasionBaseMin = 254, EvasionBaseMax = 292, MovementPenalty = 3, },
	req = { level = 46, str = 68, dex = 68, },
}
itemBases["지휘관의 브리간딘"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 275, ArmourBaseMax = 325, EvasionBaseMin = 275, EvasionBaseMax = 325, MovementPenalty = 3, },
	req = { level = 50, str = 73, dex = 73, },
}
itemBases["전투용 라멜라"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 297, ArmourBaseMax = 341, EvasionBaseMin = 297, EvasionBaseMax = 341, MovementPenalty = 3, },
	req = { level = 54, str = 79, dex = 79, },
}
itemBases["용 비늘 더블릿"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 313, ArmourBaseMax = 351, EvasionBaseMin = 313, EvasionBaseMax = 351, MovementPenalty = 3, },
	req = { level = 57, str = 83, dex = 83, },
}
itemBases["사막 브리간딘"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 376, ArmourBaseMax = 451, EvasionBaseMin = 376, EvasionBaseMax = 451, MovementPenalty = 3, },
	req = { level = 60, str = 96, dex = 96, },
}
itemBases["전신 용 비늘 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, str_dex_armour = true, top_tier_base_item_type = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 470, ArmourBaseMax = 541, EvasionBaseMin = 373, EvasionBaseMax = 429, MovementPenalty = 3, },
	req = { level = 63, str = 115, dex = 94, },
}
itemBases["장군의 브리간딘"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, str_dex_armour = true, top_tier_base_item_type = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 415, ArmourBaseMax = 465, EvasionBaseMin = 415, EvasionBaseMax = 465, MovementPenalty = 3, },
	req = { level = 66, str = 103, dex = 103, },
}
itemBases["승리의 라멜라"] = {
	type = "Body Armour",
	subType = "Armour/Evasion",
	socketLimit = 6,
	tags = { body_armour = true, str_dex_armour = true, top_tier_base_item_type = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 380, ArmourBaseMax = 437, EvasionBaseMin = 477, EvasionBaseMax = 549, MovementPenalty = 3, },
	req = { level = 69, str = 95, dex = 116, },
}

itemBases["사슬 조끼"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 27, ArmourBaseMax = 38, EnergyShieldBaseMin = 9, EnergyShieldBaseMax = 13, MovementPenalty = 5, },
	req = { str = 10, int = 10, },
}
itemBases["사슬 튜닉"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 48, ArmourBaseMax = 63, EnergyShieldBaseMin = 13, EnergyShieldBaseMax = 17, MovementPenalty = 5, },
	req = { level = 8, str = 16, int = 16, },
}
itemBases["외투 고리 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 97, ArmourBaseMax = 121, EnergyShieldBaseMin = 22, EnergyShieldBaseMax = 28, MovementPenalty = 5, },
	req = { level = 17, str = 28, int = 28, },
}
itemBases["사슬 더블릿"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 119, ArmourBaseMax = 140, EnergyShieldBaseMin = 27, EnergyShieldBaseMax = 31, MovementPenalty = 5, },
	req = { level = 21, str = 34, int = 34, },
}
itemBases["전신 고리 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 156, ArmourBaseMax = 180, EnergyShieldBaseMin = 34, EnergyShieldBaseMax = 39, MovementPenalty = 5, },
	req = { level = 28, str = 43, int = 43, },
}
itemBases["전신 사슬 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 178, ArmourBaseMax = 199, EnergyShieldBaseMin = 38, EnergyShieldBaseMax = 43, MovementPenalty = 5, },
	req = { level = 32, str = 48, int = 48, },
}
itemBases["성스러운 사슬 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 194, ArmourBaseMax = 233, EnergyShieldBaseMin = 41, EnergyShieldBaseMax = 49, MovementPenalty = 5, },
	req = { level = 35, str = 53, int = 53, },
}
itemBases["격자형 고리 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 216, ArmourBaseMax = 248, EnergyShieldBaseMin = 45, EnergyShieldBaseMax = 52, MovementPenalty = 5, },
	req = { level = 39, str = 59, int = 59, },
}
itemBases["십자군 사슬 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 237, ArmourBaseMax = 266, EnergyShieldBaseMin = 50, EnergyShieldBaseMax = 55, MovementPenalty = 5, },
	req = { level = 43, str = 64, int = 64, },
}
itemBases["화려한 고리 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 259, ArmourBaseMax = 298, EnergyShieldBaseMin = 54, EnergyShieldBaseMax = 62, MovementPenalty = 5, },
	req = { level = 47, str = 69, int = 69, },
}
itemBases["쇠사슬 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 281, ArmourBaseMax = 314, EnergyShieldBaseMin = 58, EnergyShieldBaseMax = 65, MovementPenalty = 5, },
	req = { level = 51, str = 75, int = 75, },
}
itemBases["신도 사슬 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 302, ArmourBaseMax = 363, EnergyShieldBaseMin = 62, EnergyShieldBaseMax = 74, MovementPenalty = 5, },
	req = { level = 55, str = 80, int = 80, },
}
itemBases["단단한 고리 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 325, ArmourBaseMax = 374, EnergyShieldBaseMin = 66, EnergyShieldBaseMax = 76, MovementPenalty = 5, },
	req = { level = 58, str = 84, int = 84, },
}
itemBases["점령자의 사슬 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 387, ArmourBaseMax = 445, EnergyShieldBaseMin = 79, EnergyShieldBaseMax = 91, MovementPenalty = 5, },
	req = { level = 61, str = 96, int = 96, },
}
itemBases["고상한 고리 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, str_int_armour = true, top_tier_base_item_type = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 377, ArmourBaseMax = 433, EnergyShieldBaseMin = 92, EnergyShieldBaseMax = 105, MovementPenalty = 5, },
	req = { level = 64, str = 90, int = 105, },
}
itemBases["성인의 쇠사슬 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, str_int_armour = true, top_tier_base_item_type = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 443, ArmourBaseMax = 496, EnergyShieldBaseMin = 76, EnergyShieldBaseMax = 85, MovementPenalty = 5, },
	req = { level = 67, str = 109, int = 94, },
}
itemBases["성인의 사슬 갑옷"] = {
	type = "Body Armour",
	subType = "Armour/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, str_int_armour = true, top_tier_base_item_type = true, armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 401, ArmourBaseMax = 461, EnergyShieldBaseMin = 96, EnergyShieldBaseMax = 110, MovementPenalty = 5, },
	req = { level = 70, str = 99, int = 115, },
}

itemBases["패드 조끼"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 27, EvasionBaseMax = 38, EnergyShieldBaseMin = 9, EnergyShieldBaseMax = 13, MovementPenalty = 3, },
	req = { dex = 10, int = 10, },
}
itemBases["기름칠된 조끼"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 54, EvasionBaseMax = 70, EnergyShieldBaseMin = 14, EnergyShieldBaseMax = 18, MovementPenalty = 3, },
	req = { level = 9, dex = 17, int = 17, },
}
itemBases["패드 재킷"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 102, EvasionBaseMax = 128, EnergyShieldBaseMin = 24, EnergyShieldBaseMax = 29, MovementPenalty = 3, },
	req = { level = 18, dex = 30, int = 30, },
}
itemBases["기름칠된 외투"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 124, EvasionBaseMax = 146, EnergyShieldBaseMin = 28, EnergyShieldBaseMax = 33, MovementPenalty = 3, },
	req = { level = 22, dex = 35, int = 35, },
}
itemBases["다홍색 의복"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 156, EvasionBaseMax = 180, EnergyShieldBaseMin = 34, EnergyShieldBaseMax = 39, MovementPenalty = 3, },
	req = { level = 28, dex = 43, int = 43, },
}
itemBases["밀랍재질 의복"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 178, EvasionBaseMax = 205, EnergyShieldBaseMin = 38, EnergyShieldBaseMax = 44, MovementPenalty = 3, },
	req = { level = 32, dex = 48, int = 48, },
}
itemBases["뼈 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 194, EvasionBaseMax = 233, EnergyShieldBaseMin = 41, EnergyShieldBaseMax = 49, MovementPenalty = 3, },
	req = { level = 35, dex = 53, int = 53, },
}
itemBases["누비 재킷"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 221, EvasionBaseMax = 248, EnergyShieldBaseMin = 46, EnergyShieldBaseMax = 52, MovementPenalty = 3, },
	req = { level = 40, dex = 60, int = 60, },
}
itemBases["매끈한 외투"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 243, EvasionBaseMax = 287, EnergyShieldBaseMin = 51, EnergyShieldBaseMax = 60, MovementPenalty = 3, },
	req = { level = 44, dex = 65, int = 65, },
}
itemBases["진홍색 의복"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 264, EvasionBaseMax = 304, EnergyShieldBaseMin = 55, EnergyShieldBaseMax = 63, MovementPenalty = 3, },
	req = { level = 48, dex = 71, int = 71, },
}
itemBases["옻칠한 의복"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 286, EvasionBaseMax = 329, EnergyShieldBaseMin = 59, EnergyShieldBaseMax = 68, MovementPenalty = 3, },
	req = { level = 52, dex = 76, int = 76, },
}
itemBases["지하실 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 308, EvasionBaseMax = 369, EnergyShieldBaseMin = 63, EnergyShieldBaseMax = 76, MovementPenalty = 3, },
	req = { level = 56, dex = 82, int = 82, },
}
itemBases["파수꾼 재킷"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 330, EvasionBaseMax = 370, EnergyShieldBaseMin = 67, EnergyShieldBaseMax = 76, MovementPenalty = 3, },
	req = { level = 59, dex = 86, int = 86, },
}
itemBases["광택 나는 외투"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 387, EvasionBaseMax = 434, EnergyShieldBaseMin = 79, EnergyShieldBaseMax = 89, MovementPenalty = 3, },
	req = { level = 62, dex = 96, int = 96, },
}
itemBases["피의 의복"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, armour = true, default = true, dex_int_armour = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 436, EvasionBaseMax = 501, EnergyShieldBaseMin = 73, EnergyShieldBaseMax = 84, MovementPenalty = 3, },
	req = { level = 65, dex = 107, int = 90, },
}
itemBases["가학자 의복"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, armour = true, default = true, dex_int_armour = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 427, EvasionBaseMax = 491, EnergyShieldBaseMin = 93, EnergyShieldBaseMax = 107, MovementPenalty = 3, },
	req = { level = 68, dex = 103, int = 109, },
}
itemBases["육욕의 갑옷"] = {
	type = "Body Armour",
	subType = "Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, top_tier_base_item_type = true, armour = true, default = true, dex_int_armour = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicit = "마나 최대치 +(20-25)",
	implicitModTypes = { { "resource", "mana" }, },
	armour = { EvasionBaseMin = 353, EvasionBaseMax = 388, EnergyShieldBaseMin = 103, EnergyShieldBaseMax = 113, MovementPenalty = 3, },
	req = { level = 71, dex = 88, int = 122, },
}

itemBases["희생의 의복"] = {
	type = "Body Armour",
	subType = "Armour/Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, str_dex_int_armour = true, armour = true, not_for_sale = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicit = "모든 바알 스킬 젬 레벨 +1",
	implicitModTypes = { { "gem" }, },
	armour = { ArmourBaseMin = 329, ArmourBaseMax = 378, EvasionBaseMin = 329, EvasionBaseMax = 378, EnergyShieldBaseMin = 67, EnergyShieldBaseMax = 77, MovementPenalty = 3, },
	req = { level = 72, str = 66, dex = 66, int = 66, },
}
itemBases["탐욕스러운 사슬옷"] = {
	type = "Body Armour",
	subType = "Armour/Evasion/Energy Shield",
	socketLimit = 6,
	tags = { body_armour = true, str_dex_int_armour = true, armour = true, not_for_sale = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 217, ArmourBaseMax = 250, EvasionBaseMin = 217, EvasionBaseMax = 250, EnergyShieldBaseMin = 44, EnergyShieldBaseMax = 51, MovementPenalty = 3, },
	req = { level = 70, str = 60, dex = 60, int = 60, },
}
itemBases["황금 외투"] = {
	type = "Body Armour",
	subType = "Armour/Evasion/Energy Shield",
	hidden = true,
	socketLimit = 6,
	tags = { body_armour = true, str_dex_int_armour = true, demigods = true, armour = true, not_for_sale = true, default = true, },
	influenceTags = { shaper = "body_armour_shaper", elder = "body_armour_elder", adjudicator = "body_armour_adjudicator", basilisk = "body_armour_basilisk", crusader = "body_armour_crusader", eyrie = "body_armour_eyrie", cleansing = "body_armour_cleansing", tangle = "body_armour_tangle" },
	implicit = "모든 원소 저항 +(15-25)%",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { ArmourBaseMin = 75, ArmourBaseMax = 86, EvasionBaseMin = 75, EvasionBaseMax = 86, EnergyShieldBaseMin = 17, EnergyShieldBaseMax = 19, },
	req = { level = 20, str = 8, dex = 8, int = 8, },
}
