-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["조잡한 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 5, PhysicalMax = 13, CritChanceBase = 5, AttackRateBase = 1.4, Range = 120, },
	req = { dex = 14, },
}
itemBases["단궁"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 6, PhysicalMax = 16, CritChanceBase = 5, AttackRateBase = 1.5, Range = 120, },
	req = { level = 5, dex = 26, },
}
itemBases["장궁"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 8, PhysicalMax = 33, CritChanceBase = 6, AttackRateBase = 1.3, Range = 120, },
	req = { level = 9, dex = 38, },
}
itemBases["합성궁"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 16, PhysicalMax = 34, CritChanceBase = 6, AttackRateBase = 1.3, Range = 120, },
	req = { level = 14, dex = 53, },
}
itemBases["반곡궁"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "일반 치명타 피해 배율 +(15-25)%",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 15, PhysicalMax = 45, CritChanceBase = 6.7, AttackRateBase = 1.25, Range = 120, },
	req = { level = 18, dex = 65, },
}
itemBases["뼈 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 15, PhysicalMax = 45, CritChanceBase = 6.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 23, dex = 80, },
}
itemBases["왕실 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "공격 스킬의 원소 피해 (20-24)% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "attack" }, },
	weapon = { PhysicalMin = 14, PhysicalMax = 56, CritChanceBase = 5, AttackRateBase = 1.45, Range = 120, },
	req = { level = 28, dex = 95, },
}
itemBases["죽음의 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "치명타 확률 (30-50)% 증가",
	implicitModTypes = { { "attack", "critical" }, },
	weapon = { PhysicalMin = 28, PhysicalMax = 73, CritChanceBase = 5, AttackRateBase = 1.2, Range = 120, },
	req = { level = 32, dex = 107, },
}
itemBases["반동궁"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "이동 속도 6% 증가",
	implicitModTypes = { { "speed" }, },
	weapon = { PhysicalMin = 37, PhysicalMax = 56, CritChanceBase = 5.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 36, dex = 124, },
}
itemBases["수목원 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 20, PhysicalMax = 61, CritChanceBase = 5, AttackRateBase = 1.5, Range = 120, },
	req = { level = 35, dex = 116, },
}
itemBases["비곡궁"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 24, PhysicalMax = 96, CritChanceBase = 6, AttackRateBase = 1.25, Range = 120, },
	req = { level = 38, dex = 125, },
}
itemBases["복합궁"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 37, PhysicalMax = 76, CritChanceBase = 6, AttackRateBase = 1.3, Range = 120, },
	req = { level = 41, dex = 134, },
}
itemBases["저격수 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "일반 치명타 피해 배율 +(15-25)%",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 32, PhysicalMax = 96, CritChanceBase = 6.7, AttackRateBase = 1.25, Range = 120, },
	req = { level = 44, dex = 143, },
}
itemBases["상아색 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 29, PhysicalMax = 86, CritChanceBase = 6.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 47, dex = 152, },
}
itemBases["명문가의 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "공격 스킬의 원소 피해 (20-24)% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "attack" }, },
	weapon = { PhysicalMin = 24, PhysicalMax = 94, CritChanceBase = 5, AttackRateBase = 1.45, Range = 120, },
	req = { level = 50, dex = 161, },
}
itemBases["대량 학살의 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "치명타 확률 (30-50)% 증가",
	implicitModTypes = { { "attack", "critical" }, },
	weapon = { PhysicalMin = 44, PhysicalMax = 116, CritChanceBase = 5, AttackRateBase = 1.2, Range = 120, },
	req = { level = 53, dex = 170, },
}
itemBases["강철목 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "이동 속도 6% 증가",
	implicitModTypes = { { "speed" }, },
	weapon = { PhysicalMin = 58, PhysicalMax = 86, CritChanceBase = 5.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 57, dex = 190, },
}
itemBases["잡목림 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 32, PhysicalMax = 96, CritChanceBase = 5, AttackRateBase = 1.5, Range = 120, },
	req = { level = 56, dex = 179, },
}
itemBases["성채 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 36, PhysicalMax = 144, CritChanceBase = 6, AttackRateBase = 1.25, Range = 120, },
	req = { level = 58, dex = 185, },
}
itemBases["레인저 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 56, PhysicalMax = 117, CritChanceBase = 6, AttackRateBase = 1.3, Range = 120, },
	req = { level = 60, dex = 212, },
}
itemBases["암살자 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, top_tier_base_item_type = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "일반 치명타 피해 배율 +(15-25)%",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 43, PhysicalMax = 130, CritChanceBase = 6.7, AttackRateBase = 1.25, Range = 120, },
	req = { level = 62, dex = 212, },
}
itemBases["척추 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, top_tier_base_item_type = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 38, PhysicalMax = 115, CritChanceBase = 6.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 64, dex = 212, },
}
itemBases["제국 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, top_tier_base_item_type = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "공격 스킬의 원소 피해 (20-24)% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "attack" }, },
	weapon = { PhysicalMin = 29, PhysicalMax = 117, CritChanceBase = 5, AttackRateBase = 1.45, Range = 120, },
	req = { level = 66, dex = 212, },
}
itemBases["선구자 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, top_tier_base_item_type = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "치명타 확률 (30-50)% 증가",
	implicitModTypes = { { "attack", "critical" }, },
	weapon = { PhysicalMin = 50, PhysicalMax = 133, CritChanceBase = 5, AttackRateBase = 1.2, Range = 120, },
	req = { level = 68, dex = 212, },
}
itemBases["마라케스 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, ranged = true, weapon = true, default = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "이동 속도 10% 증가",
	implicitModTypes = { { "speed" }, },
	weapon = { PhysicalMin = 61, PhysicalMax = 92, CritChanceBase = 5.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 71, dex = 222, },
}
itemBases["다면체 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, default = true, not_for_sale = true, ranged = true, weapon = true, experimental_base = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "화염 피해 (40-48)~(60-72) 추가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "fire", "attack" }, },
	weapon = { PhysicalMin = 9, PhysicalMax = 13, CritChanceBase = 5.5, AttackRateBase = 1.3, Range = 120, },
	req = { level = 30, dex = 101, },
}
itemBases["주물 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, default = true, not_for_sale = true, ranged = true, weapon = true, experimental_base = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "화염 피해 (70-84)~(110-124) 추가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "fire", "attack" }, },
	weapon = { PhysicalMin = 13, PhysicalMax = 20, CritChanceBase = 5.5, AttackRateBase = 1.3, Range = 120, },
	req = { level = 50, dex = 161, },
}
itemBases["태양의 활"] = {
	type = "Bow",
	socketLimit = 6,
	tags = { two_hand_weapon = true, default = true, not_for_sale = true, ranged = true, weapon = true, experimental_base = true, twohand = true, bow = true, },
	influenceTags = { shaper = "bow_shaper", elder = "bow_elder", adjudicator = "bow_adjudicator", basilisk = "bow_basilisk", crusader = "bow_crusader", eyrie = "bow_eyrie", cleansing = "bow_cleansing", tangle = "bow_tangle" },
	implicit = "화염 피해 (105-116)~(160-172) 추가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "fire", "attack" }, },
	weapon = { PhysicalMin = 16, PhysicalMax = 24, CritChanceBase = 5.5, AttackRateBase = 1.3, Range = 120, },
	req = { level = 70, dex = 212, },
}
