-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["유리 단도"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 6, PhysicalMax = 10, CritChanceBase = 6, AttackRateBase = 1.5, Range = 10, },
	req = { dex = 9, int = 6, },
}
itemBases["무두질용 단도"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 4, PhysicalMax = 17, CritChanceBase = 6, AttackRateBase = 1.45, Range = 10, },
	req = { level = 5, dex = 16, int = 11, },
}
itemBases["스틸레토"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 7, PhysicalMax = 27, CritChanceBase = 6.1, AttackRateBase = 1.5, Range = 10, },
	req = { level = 15, dex = 30, int = 30, },
}
itemBases["갈래 단검"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { maraketh = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "4%의 확률로 공격 피해를 막아냄",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 14, PhysicalMax = 54, CritChanceBase = 6.2, AttackRateBase = 1.35, Range = 10, },
	req = { level = 36, dex = 55, int = 77, },
}
itemBases["박피 단도"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 45, CritChanceBase = 6, AttackRateBase = 1.4, Range = 10, },
	req = { level = 30, dex = 64, int = 44, },
}
itemBases["포이너드"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 13, PhysicalMax = 52, CritChanceBase = 6.1, AttackRateBase = 1.5, Range = 10, },
	req = { level = 41, dex = 72, int = 72, },
}
itemBases["트리술라"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { maraketh = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "4%의 확률로 공격 피해를 막아냄",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 74, CritChanceBase = 6.5, AttackRateBase = 1.35, Range = 10, },
	req = { level = 51, dex = 83, int = 99, },
}
itemBases["내장 제거용 단도"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 76, CritChanceBase = 6.5, AttackRateBase = 1.4, Range = 10, },
	req = { level = 56, dex = 113, int = 78, },
}
itemBases["매복자"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 74, CritChanceBase = 6.1, AttackRateBase = 1.5, Range = 10, },
	req = { level = 60, dex = 113, int = 113, },
}
itemBases["사이"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { maraketh = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "6%의 확률로 공격 피해를 막아냄",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 22, PhysicalMax = 88, CritChanceBase = 6.2, AttackRateBase = 1.35, Range = 10, },
	req = { level = 70, dex = 121, int = 121, },
}
itemBases["중공 단검"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { weapon = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, experimental_base = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "이 무기로 주는 모든 명중 피해가 중독 유발 가능",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 12, PhysicalMax = 46, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 30, dex = 54, int = 54, },
}
itemBases["가압 단검"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { weapon = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, experimental_base = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "이 무기로 주는 모든 명중 피해가 중독 유발 가능",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 71, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 50, dex = 86, int = 86, },
}
itemBases["공압 단검"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { weapon = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, experimental_base = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicit = "이 무기로 주는 모든 명중 피해가 중독 유발 가능",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 79, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 70, dex = 121, int = 121, },
}
itemBases["천상의 칼날"] = {
	type = "Dagger",
	hidden = true,
	socketLimit = 3,
	tags = { one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	influenceTags = { shaper = "dagger_shaper", elder = "dagger_elder", adjudicator = "dagger_adjudicator", basilisk = "dagger_basilisk", crusader = "dagger_crusader", eyrie = "dagger_eyrie", cleansing = "dagger_cleansing", tangle = "dagger_tangle" },
	implicitModTypes = { },
	weapon = { PhysicalMin = 4, PhysicalMax = 8, CritChanceBase = 6, AttackRateBase = 1.5, Range = 10, },
	req = { dex = 9, int = 6, },
}

itemBases["조각용 단도"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 3, PhysicalMax = 26, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 10, dex = 18, int = 26, },
}
itemBases["주머니 단도"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 8, PhysicalMax = 34, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 20, dex = 31, int = 45, },
}
itemBases["구리 크리스"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 50% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 10, PhysicalMax = 41, CritChanceBase = 6.5, AttackRateBase = 1.3, Range = 10, },
	req = { level = 24, dex = 28, int = 60, },
}
itemBases["양날 단검"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 43, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 28, dex = 42, int = 60, },
}
itemBases["임프 단검"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 40% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 15, PhysicalMax = 59, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 32, dex = 36, int = 78, },
}
itemBases["도살자 단도"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 7, PhysicalMax = 62, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 38, dex = 55, int = 79, },
}
itemBases["주머니칼"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 15, PhysicalMax = 59, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 44, dex = 63, int = 90, },
}
itemBases["황금 크리스"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 50% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 75, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 47, dex = 51, int = 110, },
}
itemBases["왕실 양날 단검"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 16, PhysicalMax = 64, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 50, dex = 71, int = 102, },
}
itemBases["마귀 단검"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 40% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 22, PhysicalMax = 87, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 53, dex = 58, int = 123, },
}
itemBases["살육 단도"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 10, PhysicalMax = 86, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 58, dex = 81, int = 117, },
}
itemBases["에조미어 단검"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, top_tier_base_item_type = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 79, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 62, dex = 95, int = 131, },
}
itemBases["백금 크리스"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, top_tier_base_item_type = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 50% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 24, PhysicalMax = 95, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 64, dex = 76, int = 149, },
}
itemBases["제국 양날 단검"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, top_tier_base_item_type = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 30% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 73, CritChanceBase = 6.3, AttackRateBase = 1.5, Range = 10, },
	req = { level = 66, dex = 95, int = 131, },
}
itemBases["악마 단검"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, top_tier_base_item_type = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "일반 치명타 확률 40% 증가",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 24, PhysicalMax = 97, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 68, dex = 76, int = 149, },
}
itemBases["일렁이는 화염 칼"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { weapon = true, onehand = true, not_for_sale = true, one_hand_weapon = true, experimental_base = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "장착된 스킬 사용 시 10레벨 화염 질주 발동",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 12, PhysicalMax = 47, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 30, dex = 54, int = 54, },
}
itemBases["번쩍이는 불꽃 칼"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { weapon = true, onehand = true, not_for_sale = true, one_hand_weapon = true, experimental_base = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "장착된 스킬 사용 시 20레벨 화염 질주 발동",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 73, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 50, dex = 86, int = 86, },
}
itemBases["지옥불 칼"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { weapon = true, onehand = true, not_for_sale = true, one_hand_weapon = true, experimental_base = true, dagger = true, default = true, },
	influenceTags = { shaper = "rune_dagger_shaper", elder = "rune_dagger_elder", adjudicator = "rune_dagger_adjudicator", basilisk = "rune_dagger_basilisk", crusader = "rune_dagger_crusader", eyrie = "rune_dagger_eyrie", cleansing = "rune_dagger_cleansing", tangle = "rune_dagger_tangle" },
	implicit = "장착된 스킬 사용 시 30레벨 화염 질주 발동",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 85, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 70, dex = 121, int = 121, },
}
