-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["소형 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 70, duration = 3, chargesUsed = 7, chargesMax = 21, },
	req = { },
}
itemBases["중형 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 150, duration = 3.5, chargesUsed = 8, chargesMax = 28, },
	req = { level = 3, },
}
itemBases["대형 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 250, duration = 3.5, chargesUsed = 9, chargesMax = 30, },
	req = { level = 6, },
}
itemBases["대용량 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 360, duration = 3.5, chargesUsed = 10, chargesMax = 32, },
	req = { level = 12, },
}
itemBases["거대 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 640, duration = 3, chargesUsed = 10, chargesMax = 25, },
	req = { level = 18, },
}
itemBases["초거대 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 830, duration = 4, chargesUsed = 10, chargesMax = 30, },
	req = { level = 24, },
}
itemBases["초대형 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 1000, duration = 3.5, chargesUsed = 10, chargesMax = 32, },
	req = { level = 30, },
}
itemBases["성스러운 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 1200, duration = 3, chargesUsed = 10, chargesMax = 25, },
	req = { level = 36, },
}
itemBases["거룩한 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 1990, duration = 4, chargesUsed = 10, chargesMax = 30, },
	req = { level = 42, },
}
itemBases["축성된 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 1460, duration = 1.5, chargesUsed = 15, chargesMax = 30, },
	req = { level = 50, },
}
itemBases["신성한 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, not_for_sale = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 2400, duration = 3.5, chargesUsed = 15, chargesMax = 45, },
	req = { level = 60, },
}
itemBases["영원의 생명력 플라스크"] = {
	type = "Flask",
	subType = "Life",
	tags = { flask = true, not_for_sale = true, life_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 2080, duration = 2, chargesUsed = 15, chargesMax = 45, },
	req = { level = 65, },
}

itemBases["소형 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 50, duration = 3, chargesUsed = 6, chargesMax = 24, },
	req = { },
}
itemBases["중형 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 70, duration = 3.5, chargesUsed = 7, chargesMax = 30, },
	req = { level = 3, },
}
itemBases["대형 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 90, duration = 4, chargesUsed = 8, chargesMax = 35, },
	req = { level = 6, },
}
itemBases["대용량 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 120, duration = 4, chargesUsed = 9, chargesMax = 36, },
	req = { level = 12, },
}
itemBases["거대 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 170, duration = 4.5, chargesUsed = 7, chargesMax = 30, },
	req = { level = 18, },
}
itemBases["초거대 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 250, duration = 5, chargesUsed = 8, chargesMax = 36, },
	req = { level = 24, },
}
itemBases["초대형 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 350, duration = 5, chargesUsed = 8, chargesMax = 38, },
	req = { level = 30, },
}
itemBases["성스러운 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 480, duration = 5.5, chargesUsed = 7, chargesMax = 35, },
	req = { level = 36, },
}
itemBases["거룩한 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 700, duration = 6, chargesUsed = 6, chargesMax = 30, },
	req = { level = 42, },
}
itemBases["축성된 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 1100, duration = 6.5, chargesUsed = 7, chargesMax = 35, },
	req = { level = 50, },
}
itemBases["신성한 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, not_for_sale = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 1400, duration = 5, chargesUsed = 8, chargesMax = 42, },
	req = { level = 60, },
}
itemBases["영원의 마나 플라스크"] = {
	type = "Flask",
	subType = "Mana",
	tags = { flask = true, not_for_sale = true, mana_flask = true, default = true, },
	implicitModTypes = { },
	flask = { mana = 1800, duration = 7, chargesUsed = 8, chargesMax = 42, },
	req = { level = 65, },
}

itemBases["소형 하이브리드 플라스크"] = {
	type = "Flask",
	subType = "Hybrid",
	tags = { flask = true, hybrid_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 100, mana = 70, duration = 5, chargesUsed = 20, chargesMax = 40, },
	req = { level = 10, },
}
itemBases["중형 하이브리드 플라스크"] = {
	type = "Flask",
	subType = "Hybrid",
	tags = { flask = true, hybrid_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 230, mana = 100, duration = 5, chargesUsed = 20, chargesMax = 40, },
	req = { level = 20, },
}
itemBases["대형 하이브리드 플라스크"] = {
	type = "Flask",
	subType = "Hybrid",
	tags = { flask = true, hybrid_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 510, mana = 140, duration = 5, chargesUsed = 20, chargesMax = 40, },
	req = { level = 30, },
}
itemBases["초대형 하이브리드 플라스크"] = {
	type = "Flask",
	subType = "Hybrid",
	tags = { flask = true, hybrid_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 690, mana = 200, duration = 5, chargesUsed = 20, chargesMax = 40, },
	req = { level = 40, },
}
itemBases["성스러운 하이브리드 플라스크"] = {
	type = "Flask",
	subType = "Hybrid",
	tags = { flask = true, hybrid_flask = true, default = true, },
	implicitModTypes = { },
	flask = { life = 1440, mana = 400, duration = 5, chargesUsed = 20, chargesMax = 40, },
	req = { level = 50, },
}
itemBases["거룩한 하이브리드 플라스크"] = {
	type = "Flask",
	subType = "Hybrid",
	tags = { flask = true, hybrid_flask = true, not_for_sale = true, default = true, },
	implicitModTypes = { },
	flask = { life = 1740, mana = 480, duration = 5, chargesUsed = 20, chargesMax = 40, },
	req = { level = 60, },
}

itemBases["다이아몬드 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 6, chargesUsed = 20, chargesMax = 40, buff = { "일반 치명타 확률 100% 증가" }, },
	req = { level = 27, },
}
itemBases["루비 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 8, chargesUsed = 20, chargesMax = 50, buff = { "화염 저항 +50%", "받는 화염 피해 20% 감폭" }, },
	req = { level = 18, },
}
itemBases["사파이어 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 8, chargesUsed = 20, chargesMax = 50, buff = { "냉기 저항 +50%", "받는 냉기 피해 20% 감폭" }, },
	req = { level = 18, },
}
itemBases["토파즈 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 8, chargesUsed = 20, chargesMax = 50, buff = { "번개 저항 +50%", "받는 번개 피해 20% 감폭" }, },
	req = { level = 18, },
}
itemBases["화강암 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 6, chargesUsed = 30, chargesMax = 60, buff = { "방어도 +1500" }, },
	req = { level = 27, },
}
itemBases["수은 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 6, chargesUsed = 30, chargesMax = 60, buff = { "이동 속도 40% 증가" }, },
	req = { level = 4, },
}
itemBases["자수정 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 6.5, chargesUsed = 35, chargesMax = 65, buff = { "카오스 저항 +35%" }, },
	req = { level = 18, },
}
itemBases["석영 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 6, chargesUsed = 30, chargesMax = 60, buff = { "주문 피해 억제 확률 +10%", "차원 능력" }, },
	req = { level = 27, },
}
itemBases["비취 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 6, chargesUsed = 30, chargesMax = 60, buff = { "회피 +1500" }, },
	req = { level = 27, },
}
itemBases["현무암 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicit = "사용 시 주변의 적 도발",
	implicitModTypes = { { "flask" }, },
	flask = { duration = 8, chargesUsed = 40, chargesMax = 60, buff = { "방어도 20% 증폭" }, },
	req = { level = 27, },
}
itemBases["아쿠아마린 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicit = "사용 시 얼음 지대 생성",
	implicitModTypes = { { "flask" }, },
	flask = { duration = 8, chargesUsed = 20, chargesMax = 50, buff = { "플레이어에게 적용되는 동결 효과 60% 감소" }, },
	req = { level = 27, },
}
itemBases["휘안석 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicit = "사용 시 연막 생성",
	implicitModTypes = { { "flask" }, },
	flask = { duration = 8, chargesUsed = 40, chargesMax = 60, buff = { "회피 20% 증폭" }, },
	req = { level = 27, },
}
itemBases["유황 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicit = "사용 시 신성화 지대 생성",
	implicitModTypes = { { "flask" }, },
	flask = { duration = 8, chargesUsed = 40, chargesMax = 60, buff = { "피해 40% 증가" }, },
	req = { level = 27, },
}
itemBases["은 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 6, chargesUsed = 40, chargesMax = 60, buff = { "맹공" }, },
	req = { level = 27, },
}
itemBases["비스무트 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 8.5, chargesUsed = 15, chargesMax = 40, buff = { "모든 원소 저항 +35%" }, },
	req = { level = 8, },
}
itemBases["황금 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 5, chargesUsed = 60, chargesMax = 80, buff = { "발견하는 아이템 희귀도 30% 증가" }, },
	req = { level = 27, },
}
itemBases["강옥 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, default = true, },
	implicitModTypes = { },
	flask = { duration = 7.5, chargesUsed = 20, chargesMax = 50, buff = { "기절 한계치 30% 증가", "효과를 받는 동안 기절하는 경우 기절할 수 없음" }, },
	req = { level = 27, },
}
itemBases["철 플라스크"] = {
	type = "Flask",
	subType = "Utility",
	tags = { flask = true, utility_flask = true, not_for_sale = true, expedition_flask = true, default = true, },
	implicit = "사용 시 수호 회복",
	implicitModTypes = { { "flask" }, },
	flask = { duration = 5, chargesUsed = 40, chargesMax = 60, buff = { "수호 +200" }, },
	req = { level = 27, },
}
