-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["철제 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 9, ArmourBaseMax = 13, },
	req = { str = 9, },
}
itemBases["원뿔 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 38, ArmourBaseMax = 50, },
	req = { level = 7, str = 21, },
}
itemBases["철갑 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 92, ArmourBaseMax = 115, },
	req = { level = 18, str = 42, },
}
itemBases["폐쇄형 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 130, ArmourBaseMax = 150, },
	req = { level = 26, str = 58, },
}
itemBases["검투사 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 174, ArmourBaseMax = 195, },
	req = { level = 35, str = 75, },
}
itemBases["강탈자 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 198, ArmourBaseMax = 233, },
	req = { level = 40, str = 85, },
}
itemBases["공성 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 237, ArmourBaseMax = 272, },
	req = { level = 48, str = 101, },
}
itemBases["삼니움 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 276, ArmourBaseMax = 325, },
	req = { level = 55, str = 114, },
}
itemBases["에조미어 기병 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 346, ArmourBaseMax = 381, },
	req = { level = 60, str = 138, },
}
itemBases["왕실 기병 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { str_armour = true, helmet = true, armour = true, top_tier_base_item_type = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 377, ArmourBaseMax = 434, },
	req = { level = 65, str = 148, },
}
itemBases["영원의 기병 투구"] = {
	type = "Helmet",
	subType = "Armour",
	socketLimit = 4,
	tags = { str_armour = true, helmet = true, armour = true, top_tier_base_item_type = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 373, ArmourBaseMax = 429, },
	req = { level = 69, str = 138, },
}

itemBases["가죽 모자"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 19, EvasionBaseMax = 27, },
	req = { dex = 13, },
}
itemBases["삼각모"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 53, EvasionBaseMax = 69, },
	req = { level = 10, dex = 27, },
}
itemBases["가죽 두건"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 101, EvasionBaseMax = 127, },
	req = { level = 20, dex = 46, },
}
itemBases["늑대 가죽모"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 150, EvasionBaseMax = 172, },
	req = { level = 30, dex = 66, },
}
itemBases["사냥꾼 두건"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 203, EvasionBaseMax = 227, },
	req = { level = 41, dex = 87, },
}
itemBases["귀족 삼각모"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 232, EvasionBaseMax = 266, },
	req = { level = 47, dex = 99, },
}
itemBases["곰 가죽모"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 276, EvasionBaseMax = 325, },
	req = { level = 55, dex = 114, },
}
itemBases["실크 두건"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 346, EvasionBaseMax = 381, },
	req = { level = 60, dex = 138, },
}
itemBases["죄인 삼각모"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { top_tier_base_item_type = true, dex_armour = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 369, EvasionBaseMax = 425, },
	req = { level = 64, dex = 138, },
}
itemBases["사자 가죽모"] = {
	type = "Helmet",
	subType = "Evasion",
	socketLimit = 4,
	tags = { top_tier_base_item_type = true, dex_armour = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 380, EvasionBaseMax = 437, },
	req = { level = 70, dex = 150, },
}

itemBases["덩굴 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 7, EnergyShieldBaseMax = 10, },
	req = { int = 13, },
}
itemBases["철제 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 12, EnergyShieldBaseMax = 15, },
	req = { level = 8, int = 23, },
}
itemBases["고문용 창살"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 20, EnergyShieldBaseMax = 25, },
	req = { level = 17, int = 40, },
}
itemBases["부족 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 28, EnergyShieldBaseMax = 33, },
	req = { level = 26, int = 58, },
}
itemBases["뼈의 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 36, EnergyShieldBaseMax = 40, },
	req = { level = 34, int = 73, },
}
itemBases["달의 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 41, EnergyShieldBaseMax = 48, },
	req = { level = 39, int = 83, },
}
itemBases["강철 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 49, EnergyShieldBaseMax = 55, },
	req = { level = 48, int = 101, },
}
itemBases["네크로맨서 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 55, EnergyShieldBaseMax = 64, },
	req = { level = 54, int = 112, },
}
itemBases["태양의 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 60, EnergyShieldBaseMax = 68, },
	req = { level = 59, int = 122, },
}
itemBases["정신의 창살"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { top_tier_base_item_type = true, int_armour = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 73, EnergyShieldBaseMax = 84, },
	req = { level = 65, int = 138, },
}
itemBases["자만의 관"] = {
	type = "Helmet",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { top_tier_base_item_type = true, int_armour = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EnergyShieldBaseMin = 80, EnergyShieldBaseMax = 92, },
	req = { level = 69, int = 154, },
}

itemBases["닳은 헬름"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 13, ArmourBaseMax = 18, EvasionBaseMin = 13, EvasionBaseMax = 18, },
	req = { str = 8, dex = 8, },
}
itemBases["샐릿"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 37, ArmourBaseMax = 48, EvasionBaseMin = 37, EvasionBaseMax = 48, },
	req = { level = 13, str = 18, dex = 18, },
}
itemBases["차양 단 샐릿"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 64, ArmourBaseMax = 80, EvasionBaseMin = 64, EvasionBaseMax = 80, },
	req = { level = 23, str = 28, dex = 28, },
}
itemBases["도금 샐릿"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 90, ArmourBaseMax = 97, EvasionBaseMin = 90, EvasionBaseMax = 97, },
	req = { level = 33, str = 38, dex = 38, },
}
itemBases["호위병 샐릿"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 98, ArmourBaseMax = 116, EvasionBaseMin = 98, EvasionBaseMax = 116, },
	req = { level = 36, str = 42, dex = 42, },
}
itemBases["검사 샐릿"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 117, ArmourBaseMax = 134, EvasionBaseMin = 117, EvasionBaseMax = 134, },
	req = { level = 43, str = 49, dex = 49, },
}
itemBases["옻칠한 투구"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 138, ArmourBaseMax = 155, EvasionBaseMin = 138, EvasionBaseMax = 155, },
	req = { level = 51, str = 57, dex = 57, },
}
itemBases["홈이 긴 배서닛"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_dex_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 160, ArmourBaseMax = 189, EvasionBaseMin = 160, EvasionBaseMax = 189, },
	req = { level = 58, str = 64, dex = 64, },
}
itemBases["돼지 머리 배서닛"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, top_tier_base_item_type = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 229, ArmourBaseMax = 263, EvasionBaseMin = 159, EvasionBaseMax = 183, },
	req = { level = 63, str = 85, dex = 62, },
}
itemBases["악몽의 배서닛"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, top_tier_base_item_type = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 162, ArmourBaseMax = 187, EvasionBaseMin = 233, EvasionBaseMax = 268, },
	req = { level = 67, str = 62, dex = 85, },
}
itemBases["슬픔 가면"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, not_for_sale = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "받는 물리 피해 -15% 추가 감소\n타쇄당함\n방어 상승 최대치 +(2-3)",
	implicitModTypes = { {  }, {  }, {  }, },
	armour = { ArmourBaseMin = 42, ArmourBaseMax = 49, EvasionBaseMin = 42, EvasionBaseMax = 49, },
	req = { level = 15, str = 20, dex = 20, },
}
itemBases["속죄 가면"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, not_for_sale = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "받는 물리 피해 -15% 추가 감소\n타쇄당함\n방어 상승 최대치 +(2-3)",
	implicitModTypes = { {  }, {  }, {  }, },
	armour = { ArmourBaseMin = 122, ArmourBaseMax = 140, EvasionBaseMin = 122, EvasionBaseMax = 140, },
	req = { level = 45, str = 51, dex = 51, },
}
itemBases["참회 가면"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, not_for_sale = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "받는 물리 피해 -15% 추가 감소\n타쇄당함\n방어 상승 최대치 +(2-3)",
	implicitModTypes = { {  }, {  }, {  }, },
	armour = { ArmourBaseMin = 185, ArmourBaseMax = 212, EvasionBaseMin = 185, EvasionBaseMax = 212, },
	req = { level = 75, str = 79, dex = 79, },
}

itemBases["녹슨 코이프"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 16, ArmourBaseMax = 22, EnergyShieldBaseMin = 5, EnergyShieldBaseMax = 7, },
	req = { level = 5, str = 9, int = 9, },
}
itemBases["병사 투구"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 34, ArmourBaseMax = 45, EnergyShieldBaseMin = 8, EnergyShieldBaseMax = 11, },
	req = { level = 12, str = 16, int = 16, },
}
itemBases["대형 투구"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 61, ArmourBaseMax = 76, EnergyShieldBaseMin = 14, EnergyShieldBaseMax = 17, },
	req = { level = 22, str = 27, int = 27, },
}
itemBases["십자군 투구"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 85, ArmourBaseMax = 95, EnergyShieldBaseMin = 18, EnergyShieldBaseMax = 20, },
	req = { level = 31, str = 36, int = 36, },
}
itemBases["쇠사슬 투구"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 101, ArmourBaseMax = 119, EnergyShieldBaseMin = 21, EnergyShieldBaseMax = 25, },
	req = { level = 37, str = 42, int = 42, },
}
itemBases["맹신자 투구"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 119, ArmourBaseMax = 137, EnergyShieldBaseMin = 25, EnergyShieldBaseMax = 29, },
	req = { level = 44, str = 50, int = 50, },
}
itemBases["대형 왕관"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 143, ArmourBaseMax = 161, EnergyShieldBaseMin = 29, EnergyShieldBaseMax = 33, },
	req = { level = 53, str = 59, int = 59, },
}
itemBases["재판관 왕관"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, str_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 160, ArmourBaseMax = 189, EnergyShieldBaseMin = 33, EnergyShieldBaseMax = 39, },
	req = { level = 58, str = 64, int = 64, },
}
itemBases["예언자 왕관"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, top_tier_base_item_type = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 224, ArmourBaseMax = 258, EnergyShieldBaseMin = 32, EnergyShieldBaseMax = 37, },
	req = { level = 63, str = 85, int = 62, },
}
itemBases["집정관 왕관"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, top_tier_base_item_type = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { ArmourBaseMin = 161, ArmourBaseMax = 185, EnergyShieldBaseMin = 51, EnergyShieldBaseMax = 58, },
	req = { level = 68, str = 62, int = 91, },
}
itemBases["임프 왕관"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, not_for_sale = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "장착한 스킬이 적중 시 화염, 냉기, 번개 노출 유발\n모든 원소 저항 -10%",
	implicitModTypes = { { "elemental", "resistance" }, { "elemental", "resistance" }, },
	armour = { ArmourBaseMin = 42, ArmourBaseMax = 49, EnergyShieldBaseMin = 10, EnergyShieldBaseMax = 12, },
	req = { level = 15, str = 20, int = 20, },
}
itemBases["악마 왕관"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, not_for_sale = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "장착한 스킬이 적중 시 화염, 냉기, 번개 노출 유발\n모든 원소 저항 -10%",
	implicitModTypes = { { "elemental", "resistance" }, { "elemental", "resistance" }, },
	armour = { ArmourBaseMin = 122, ArmourBaseMax = 140, EnergyShieldBaseMin = 25, EnergyShieldBaseMax = 29, },
	req = { level = 45, str = 51, int = 51, },
}
itemBases["대악마 왕관"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, not_for_sale = true, helmet = true, armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "장착한 스킬이 적중 시 화염, 냉기, 번개 노출 유발\n모든 원소 저항 -10%",
	implicitModTypes = { { "elemental", "resistance" }, { "elemental", "resistance" }, },
	armour = { ArmourBaseMin = 185, ArmourBaseMax = 212, EnergyShieldBaseMin = 38, EnergyShieldBaseMax = 43, },
	req = { level = 75, str = 79, int = 79, },
}
itemBases["뼈 투구"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, helmetatlas1 = true, not_for_sale = true, helmet = true, armour = true, atlas_base_type = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "소환수가 주는 피해 (15-20)% 증가",
	implicitModTypes = { { "damage", "minion" }, },
	armour = { ArmourBaseMin = 197, ArmourBaseMax = 227, EnergyShieldBaseMin = 40, EnergyShieldBaseMax = 46, },
	req = { level = 73, str = 76, int = 76, },
}

itemBases["허수아비 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 13, EvasionBaseMax = 18, EnergyShieldBaseMin = 4, EnergyShieldBaseMax = 6, },
	req = { dex = 8, int = 8, },
}
itemBases["역병 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 29, EvasionBaseMax = 38, EnergyShieldBaseMin = 7, EnergyShieldBaseMax = 10, },
	req = { level = 10, dex = 14, int = 14, },
}
itemBases["철 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 48, EvasionBaseMax = 60, EnergyShieldBaseMin = 11, EnergyShieldBaseMax = 14, },
	req = { level = 17, dex = 21, int = 21, },
}
itemBases["축제용 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 77, EvasionBaseMax = 88, EnergyShieldBaseMin = 17, EnergyShieldBaseMax = 19, },
	req = { level = 28, dex = 33, int = 33, },
}
itemBases["황금 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 96, EvasionBaseMax = 103, EnergyShieldBaseMin = 20, EnergyShieldBaseMax = 22, },
	req = { level = 35, dex = 40, int = 40, },
}
itemBases["큰까마귀 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 104, EvasionBaseMax = 119, EnergyShieldBaseMin = 22, EnergyShieldBaseMax = 25, },
	req = { level = 38, dex = 44, int = 44, },
}
itemBases["냉담한 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 122, EvasionBaseMax = 137, EnergyShieldBaseMin = 25, EnergyShieldBaseMax = 28, },
	req = { level = 45, dex = 51, int = 51, },
}
itemBases["왕 시해자 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 141, EvasionBaseMax = 158, EnergyShieldBaseMin = 29, EnergyShieldBaseMax = 32, },
	req = { level = 52, dex = 58, int = 58, },
}
itemBases["할리퀸 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { helmet = true, armour = true, dex_int_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 157, EvasionBaseMax = 185, EnergyShieldBaseMin = 32, EnergyShieldBaseMax = 38, },
	req = { level = 57, dex = 64, int = 64, },
}
itemBases["바알 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { top_tier_base_item_type = true, helmet = true, armour = true, default = true, dex_int_armour = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 207, EvasionBaseMax = 239, EnergyShieldBaseMin = 37, EnergyShieldBaseMax = 43, },
	req = { level = 62, dex = 79, int = 72, },
}
itemBases["신살자 가면"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { top_tier_base_item_type = true, helmet = true, armour = true, default = true, dex_int_armour = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { EvasionBaseMin = 190, EvasionBaseMax = 219, EnergyShieldBaseMin = 47, EnergyShieldBaseMax = 54, },
	req = { level = 67, dex = 73, int = 88, },
}
itemBases["강풍 왕관"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { not_for_sale = true, helmet = true, armour = true, default = true, dex_int_armour = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "냉기 피해 (3-4)~(5-6) 추가\n플레이어가 적중 시 냉기 저항을 실제 값보다 10% 높게 취급",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "cold" }, { "elemental_damage", "damage", "elemental", "cold" }, },
	armour = { EvasionBaseMin = 42, EvasionBaseMax = 49, EnergyShieldBaseMin = 10, EnergyShieldBaseMax = 12, },
	req = { level = 15, dex = 20, int = 20, },
}
itemBases["겨울 왕관"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { not_for_sale = true, helmet = true, armour = true, default = true, dex_int_armour = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "냉기 피해 (15-20)~(28-35) 추가\n플레이어가 적중 시 냉기 저항을 실제 값보다 10% 높게 취급",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "cold" }, { "elemental_damage", "damage", "elemental", "cold" }, },
	armour = { EvasionBaseMin = 122, EvasionBaseMax = 140, EnergyShieldBaseMin = 25, EnergyShieldBaseMax = 29, },
	req = { level = 45, dex = 51, int = 51, },
}
itemBases["눈보라 왕관"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { not_for_sale = true, helmet = true, armour = true, default = true, dex_int_armour = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "냉기 피해 (75-85)~(115-128) 추가\n플레이어가 적중 시 냉기 저항을 실제 값보다 10% 높게 취급",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "cold" }, { "elemental_damage", "damage", "elemental", "cold" }, },
	armour = { EvasionBaseMin = 185, EvasionBaseMax = 212, EnergyShieldBaseMin = 38, EnergyShieldBaseMax = 43, },
	req = { level = 75, dex = 79, int = 79, },
}

itemBases["룬 투구"] = {
	type = "Helmet",
	subType = "Ward",
	socketLimit = 4,
	tags = { not_for_sale = true, helmet = true, armour = true, ward_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { WardBaseMin = 41, WardBaseMax = 47, },
	req = { level = 25, str = 30, dex = 30, int = 30, },
}
itemBases["룬 관모"] = {
	type = "Helmet",
	subType = "Ward",
	socketLimit = 4,
	tags = { not_for_sale = true, helmet = true, armour = true, ward_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { WardBaseMin = 97, WardBaseMax = 112, },
	req = { level = 49, str = 55, dex = 55, int = 55, },
}
itemBases["룬 왕관"] = {
	type = "Helmet",
	subType = "Ward",
	socketLimit = 4,
	tags = { not_for_sale = true, helmet = true, armour = true, ward_armour = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicitModTypes = { },
	armour = { WardBaseMin = 164, WardBaseMax = 189, },
	req = { level = 68, str = 66, dex = 66, int = 66, },
}

itemBases["황금 화관"] = {
	type = "Helmet",
	socketLimit = 4,
	tags = { not_for_sale = true, helmet = true, armour = true, demigods = true, default = true, },
	influenceTags = { shaper = "helmet_shaper", elder = "helmet_elder", adjudicator = "helmet_adjudicator", basilisk = "helmet_basilisk", crusader = "helmet_crusader", eyrie = "helmet_eyrie", cleansing = "helmet_cleansing", tangle = "helmet_tangle" },
	implicit = "모든 능력치 +(16-24)",
	implicitModTypes = { { "attribute" }, },
	armour = { },
	req = { level = 12, },
}
