-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["표류목 곤봉"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 6, PhysicalMax = 8, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { str = 14, },
}
itemBases["부족 곤봉"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 8, PhysicalMax = 13, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 5, str = 26, },
}
itemBases["가시 박힌 곤봉"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 13, PhysicalMax = 16, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { level = 10, str = 41, },
}
itemBases["쇄석 망치"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 15% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 15, PhysicalMax = 27, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 15, str = 56, },
}
itemBases["전쟁 망치"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 13, PhysicalMax = 31, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { level = 20, str = 71, },
}
itemBases["톱날 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 32, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 24, str = 83, },
}
itemBases["의식용 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 15% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 32, PhysicalMax = 40, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 28, str = 95, },
}
itemBases["몽환의 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 43, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 32, str = 107, },
}
itemBases["아룡 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { maraketh = true, onehand = true, not_for_sale = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "공격 속도 4% 증가",
	implicitModTypes = { { "attack", "speed" }, },
	weapon = { PhysicalMin = 28, PhysicalMax = 42, CritChanceBase = 5, AttackRateBase = 1.35, Range = 11, },
	req = { level = 34, str = 118, },
}
itemBases["석화된 곤봉"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 31, PhysicalMax = 51, CritChanceBase = 5, AttackRateBase = 1.25, Range = 11, },
	req = { level = 35, str = 116, },
}
itemBases["가시 돋친 곤봉"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 33, PhysicalMax = 42, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 38, str = 125, },
}
itemBases["바위 분쇄기"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 15% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 37, PhysicalMax = 69, CritChanceBase = 5, AttackRateBase = 1.15, Range = 11, },
	req = { level = 41, str = 134, },
}
itemBases["전투용 망치"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 25, PhysicalMax = 59, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 44, str = 143, },
}
itemBases["테두리 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 38, PhysicalMax = 63, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 47, str = 152, },
}
itemBases["화려한 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 15% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 53, PhysicalMax = 67, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 50, str = 161, },
}
itemBases["혼령 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 33, PhysicalMax = 69, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 53, str = 170, },
}
itemBases["용 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { maraketh = true, onehand = true, not_for_sale = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "공격 속도 4% 증가",
	implicitModTypes = { { "attack", "speed" }, },
	weapon = { PhysicalMin = 44, PhysicalMax = 66, CritChanceBase = 5, AttackRateBase = 1.35, Range = 11, },
	req = { level = 55, str = 184, },
}
itemBases["선대의 곤봉"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 48, PhysicalMax = 80, CritChanceBase = 5, AttackRateBase = 1.25, Range = 11, },
	req = { level = 56, str = 179, },
}
itemBases["고기 망치"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 49, PhysicalMax = 62, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 58, str = 185, },
}
itemBases["의사봉"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 15% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 54, PhysicalMax = 101, CritChanceBase = 5, AttackRateBase = 1.15, Range = 11, },
	req = { level = 60, str = 212, },
}
itemBases["군단 망치"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, top_tier_base_item_type = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 81, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 62, str = 212, },
}
itemBases["페르나치"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, top_tier_base_item_type = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 49, PhysicalMax = 82, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 64, str = 212, },
}
itemBases["금빛 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, top_tier_base_item_type = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 15% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 65, PhysicalMax = 82, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 66, str = 212, },
}
itemBases["악몽의 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { onehand = true, top_tier_base_item_type = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "적 기절 한계치 10% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 38, PhysicalMax = 80, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 68, str = 212, },
}
itemBases["거대한 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { maraketh = true, onehand = true, not_for_sale = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "공격 속도 6% 증가",
	implicitModTypes = { { "attack", "speed" }, },
	weapon = { PhysicalMin = 49, PhysicalMax = 74, CritChanceBase = 5, AttackRateBase = 1.35, Range = 11, },
	req = { level = 70, str = 220, },
}
itemBases["조명탄 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { weapon = true, onehand = true, not_for_sale = true, mace = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "이 무기로 근접 명중 시 10레벨 불타는 충격 발동",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 41, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 30, str = 101, },
}
itemBases["균열 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { weapon = true, onehand = true, not_for_sale = true, mace = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "이 무기로 근접 명중 시 15레벨 불타는 충격 발동",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 31, PhysicalMax = 64, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 50, str = 161, },
}
itemBases["우뢰 철퇴"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { weapon = true, onehand = true, not_for_sale = true, mace = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "mace_shaper", elder = "mace_elder", adjudicator = "mace_adjudicator", basilisk = "mace_basilisk", crusader = "mace_crusader", eyrie = "mace_eyrie", cleansing = "mace_cleansing", tangle = "mace_tangle" },
	implicit = "이 무기로 근접 명중 시 20레벨 불타는 충격 발동",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 39, PhysicalMax = 81, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 70, str = 218, },
}

itemBases["표류목 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 10% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 8, PhysicalMax = 11, CritChanceBase = 6, AttackRateBase = 1.2, Range = 11, },
	req = { str = 8, int = 8, },
}
itemBases["흑단목 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 12% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 17, CritChanceBase = 6, AttackRateBase = 1.2, Range = 11, },
	req = { level = 5, str = 14, int = 14, },
}
itemBases["청동 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 12% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 15, PhysicalMax = 29, CritChanceBase = 6, AttackRateBase = 1.1, Range = 11, },
	req = { level = 10, str = 22, int = 22, },
}
itemBases["석영 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 20% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 32, CritChanceBase = 6.5, AttackRateBase = 1.1, Range = 11, },
	req = { level = 15, str = 25, int = 35, },
}
itemBases["철제 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 14% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 27, PhysicalMax = 40, CritChanceBase = 6, AttackRateBase = 1.1, Range = 11, },
	req = { level = 20, str = 38, int = 38, },
}
itemBases["오커 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 16% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 24, PhysicalMax = 45, CritChanceBase = 6, AttackRateBase = 1.15, Range = 11, },
	req = { level = 24, str = 44, int = 44, },
}
itemBases["의식용 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 16% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 50, CritChanceBase = 6, AttackRateBase = 1.2, Range = 11, },
	req = { level = 28, str = 51, int = 51, },
}
itemBases["그림자 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 22% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 29, PhysicalMax = 44, CritChanceBase = 6.2, AttackRateBase = 1.25, Range = 11, },
	req = { level = 32, str = 52, int = 62, },
}
itemBases["뿔 달린 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { maraketh = true, not_for_sale = true, onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "피해가 4%의 원소 저항 관통",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 27, PhysicalMax = 50, CritChanceBase = 6, AttackRateBase = 1.3, Range = 11, },
	req = { level = 36, str = 66, int = 66, },
}
itemBases["웃는 조각상 홀"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 18% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 24, PhysicalMax = 36, CritChanceBase = 6, AttackRateBase = 1.5, Range = 11, },
	req = { level = 35, str = 62, int = 62, },
}
itemBases["세크헴"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 18% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 30, PhysicalMax = 55, CritChanceBase = 6, AttackRateBase = 1.25, Range = 11, },
	req = { level = 38, str = 67, int = 67, },
}
itemBases["수정 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 30% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 52, CritChanceBase = 6.5, AttackRateBase = 1.25, Range = 11, },
	req = { level = 41, str = 59, int = 85, },
}
itemBases["납 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 22% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 38, PhysicalMax = 57, CritChanceBase = 6, AttackRateBase = 1.25, Range = 11, },
	req = { level = 44, str = 77, int = 77, },
}
itemBases["피의 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 24% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 30, PhysicalMax = 55, CritChanceBase = 6, AttackRateBase = 1.4, Range = 11, },
	req = { level = 47, str = 81, int = 81, },
}
itemBases["왕실의 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 24% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 34, PhysicalMax = 80, CritChanceBase = 6, AttackRateBase = 1.2, Range = 11, },
	req = { level = 50, str = 86, int = 86, },
}
itemBases["심연의 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 30% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 45, PhysicalMax = 67, CritChanceBase = 6.2, AttackRateBase = 1.25, Range = 11, },
	req = { level = 53, str = 83, int = 99, },
}
itemBases["수사슴 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { maraketh = true, not_for_sale = true, onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "피해가 4%의 원소 저항 관통",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 39, PhysicalMax = 72, CritChanceBase = 6, AttackRateBase = 1.3, Range = 11, },
	req = { level = 55, str = 98, int = 98, },
}
itemBases["카루이 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 26% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 37, PhysicalMax = 55, CritChanceBase = 6, AttackRateBase = 1.5, Range = 11, },
	req = { level = 56, str = 96, int = 96, },
}
itemBases["폭군의 세크헴"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 26% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 43, PhysicalMax = 80, CritChanceBase = 6, AttackRateBase = 1.25, Range = 11, },
	req = { level = 58, str = 99, int = 99, },
}
itemBases["오팔 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 40% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 49, PhysicalMax = 73, CritChanceBase = 6.5, AttackRateBase = 1.25, Range = 11, },
	req = { level = 60, str = 95, int = 131, },
}
itemBases["백금 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 30% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 51, PhysicalMax = 76, CritChanceBase = 6, AttackRateBase = 1.25, Range = 11, },
	req = { level = 62, str = 113, int = 113, },
}
itemBases["바알 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 32% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 37, PhysicalMax = 70, CritChanceBase = 6, AttackRateBase = 1.4, Range = 11, },
	req = { level = 64, str = 113, int = 113, },
}
itemBases["육욕의 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 32% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 41, PhysicalMax = 95, CritChanceBase = 6, AttackRateBase = 1.2, Range = 11, },
	req = { level = 66, str = 113, int = 113, },
}
itemBases["공허의 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 피해 40% 증가",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 50, PhysicalMax = 76, CritChanceBase = 6.2, AttackRateBase = 1.25, Range = 11, },
	req = { level = 68, str = 104, int = 122, },
}
itemBases["삼바 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { maraketh = true, not_for_sale = true, onehand = true, sceptre = true, mace = true, weapon = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "피해가 6%의 원소 저항 관통",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 42, PhysicalMax = 78, CritChanceBase = 6, AttackRateBase = 1.3, Range = 11, },
	req = { level = 70, str = 121, int = 113, },
}
itemBases["진동 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { weapon = true, not_for_sale = true, onehand = true, sceptre = true, mace = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 과부하",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "critical" }, },
	weapon = { PhysicalMin = 23, PhysicalMax = 34, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 11, },
	req = { level = 30, str = 44, int = 64, },
}
itemBases["안정화의 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { weapon = true, not_for_sale = true, onehand = true, sceptre = true, mace = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "원소 균형",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 52, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 11, },
	req = { level = 50, str = 71, int = 102, },
}
itemBases["갈마드는 셉터"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { weapon = true, not_for_sale = true, onehand = true, sceptre = true, mace = true, experimental_base = true, one_hand_weapon = true, default = true, },
	influenceTags = { shaper = "sceptre_shaper", elder = "sceptre_elder", adjudicator = "sceptre_adjudicator", basilisk = "sceptre_basilisk", crusader = "sceptre_crusader", eyrie = "sceptre_eyrie", cleansing = "sceptre_cleansing", tangle = "sceptre_tangle" },
	implicit = "고통의 비밀",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 41, PhysicalMax = 61, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 11, },
	req = { level = 70, str = 95, int = 131, },
}

itemBases["표류목 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 10, PhysicalMax = 16, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { str = 20, },
}
itemBases["부족 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 17, PhysicalMax = 25, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 8, str = 35, },
}
itemBases["나무 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 16, PhysicalMax = 33, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 12, str = 47, },
}
itemBases["대형 양손 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 45% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 25, PhysicalMax = 38, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 17, str = 62, },
}
itemBases["삐죽삐죽한 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 27, PhysicalMax = 49, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 22, str = 77, },
}
itemBases["황동 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 40, PhysicalMax = 60, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 27, str = 92, },
}
itemBases["섬뜩한 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 46, PhysicalMax = 62, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 32, str = 107, },
}
itemBases["모닝스타"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "효과 범위 15% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 45, PhysicalMax = 68, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 34, str = 118, },
}
itemBases["토템 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 57, PhysicalMax = 85, CritChanceBase = 5, AttackRateBase = 1.1, Range = 13, },
	req = { level = 36, str = 119, },
}
itemBases["대형 나무 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 43, PhysicalMax = 88, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 40, str = 131, },
}
itemBases["강철머리 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 45% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 54, PhysicalMax = 81, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 44, str = 143, },
}
itemBases["가시투성이 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 55, PhysicalMax = 103, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 48, str = 155, },
}
itemBases["판금 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 72, PhysicalMax = 108, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 51, str = 164, },
}
itemBases["끔찍한 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 30% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 77, PhysicalMax = 104, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 54, str = 173, },
}
itemBases["태양의 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "효과 범위 15% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 75, PhysicalMax = 113, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 56, str = 187, },
}
itemBases["카루이 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적에게 적용되는 기절 지속시간 45% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 112, PhysicalMax = 168, CritChanceBase = 5, AttackRateBase = 1, Range = 13, },
	req = { level = 57, str = 182, },
}
itemBases["초대형 나무 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "범위 피해 30% 증가",
	implicitModTypes = { { "damage" }, },
	weapon = { PhysicalMin = 65, PhysicalMax = 135, CritChanceBase = 5.5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 59, str = 188, },
}
itemBases["말뚝 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, top_tier_base_item_type = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "적 기절 한계치 20% 감소",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 77, PhysicalMax = 115, CritChanceBase = 5, AttackRateBase = 1.35, Range = 13, },
	req = { level = 61, str = 212, },
}
itemBases["고기 갈이개"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, top_tier_base_item_type = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "5%의 확률로 2배의 피해를 줌",
	implicitModTypes = { { "damage" }, },
	weapon = { PhysicalMin = 74, PhysicalMax = 138, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { level = 63, str = 212, },
}
itemBases["제국 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, top_tier_base_item_type = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "힘 10% 증가",
	implicitModTypes = { { "attribute" }, },
	weapon = { PhysicalMin = 102, PhysicalMax = 153, CritChanceBase = 5, AttackRateBase = 1.1, Range = 13, },
	req = { level = 65, str = 212, },
}
itemBases["공포의 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, top_tier_base_item_type = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "25%의 확률로 기절 지속시간 2배",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 101, PhysicalMax = 137, CritChanceBase = 6, AttackRateBase = 1.15, Range = 13, },
	req = { level = 67, str = 212, },
}
itemBases["광환의 대형 망치"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, mace = true, weapon = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "효과 범위 20% 증가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 91, PhysicalMax = 136, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 69, str = 220, },
}
itemBases["둔력 응축자"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, not_for_sale = true, mace = true, experimental_base = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "함성 사용 시 전력 공격 1회 추가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 39, PhysicalMax = 64, CritChanceBase = 5, AttackRateBase = 1.15, Range = 13, },
	req = { level = 30, str = 101, },
}
itemBases["압착력 확대자"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, not_for_sale = true, mace = true, experimental_base = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "함성 사용 시 전력 공격 1회 추가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 62, PhysicalMax = 103, CritChanceBase = 5, AttackRateBase = 1.15, Range = 13, },
	req = { level = 50, str = 161, },
}
itemBases["충격력 확산자"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, not_for_sale = true, mace = true, experimental_base = true, twohand = true, default = true, },
	influenceTags = { shaper = "2h_mace_shaper", elder = "2h_mace_elder", adjudicator = "2h_mace_adjudicator", basilisk = "2h_mace_basilisk", crusader = "2h_mace_crusader", eyrie = "2h_mace_eyrie", cleansing = "2h_mace_cleansing", tangle = "2h_mace_tangle" },
	implicit = "함성 사용 시 전력 공격 1회 추가",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 81, PhysicalMax = 135, CritChanceBase = 5, AttackRateBase = 1.15, Range = 13, },
	req = { level = 70, str = 220, },
}
