-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		lang={
			Korean={
				[1]={
					limit={
						[1]={
							[1]=1,
							[2]=1
						}
					},
					text="광선이 추가 대상 {0}개를 향해 분할"
				},
				[2]={
					limit={
						[1]={
							[1]="#",
							[2]="#"
						}
					},
					text="광선이 추가 대상 {0}개를 향해 분할"
				}
			}
		},
		name="base_split_num",
		stats={
			[1]="projectile_number_to_split"
		}
	},
	parent="skill_stat_descriptions",
	["projectile_number_to_split"]=1
}