-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Minion active skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["ChaosElementalCascadeSummoned"] = {
	name = "Cascade",
	hidden = true,
	color = 3,
	baseEffectiveness = 1.3650000095367,
	incrementalEffectiveness = 0.040600001811981,
	description = "땅에서 고드름이 솟아오르면서 잇달아 작은 폭발을 일으켜 범위 내의 적들에게 피해를 줍니다.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, [SkillType.Cold] = true, [SkillType.Physical] = true, [SkillType.CanRapidFire] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		spell = true,
		area = true,
	},
	constantStats = {
		{ "upheaval_number_of_spikes", 6 },
		{ "skill_physical_damage_%_to_convert_to_chaos", 100 },
		{ "monster_penalty_against_minions_damage_+%_final_vs_player_minions", -25 },
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"is_area_damage",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, critChance = 5, storedUses = 1, cooldown = 3, levelRequirement = 4, statInterpolation = { 3, 3, }, },
	},
}
skills["SandstormChaosElementalSummoned"] = {
	name = "Chaos Aura",
	hidden = true,
	color = 4,
	baseEffectiveness = 6.1421999931335,
	incrementalEffectiveness = 0.052099999040365,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.AreaSpell] = true, [SkillType.DamageOverTime] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		duration = true,
		area = true,
	},
	baseMods = {
		skill("dotIsArea", true),
	},
	constantStats = {
		{ "base_skill_effect_duration", 5000 },
		{ "active_skill_area_of_effect_radius_+%_final", 20 },
	},
	stats = {
		"base_chaos_damage_to_deal_per_minute",
		"is_area_damage",
		"spell_damage_modifiers_apply_to_skill_dot",
	},
	levels = {
		[1] = { 16.666667039196, storedUses = 1, levelRequirement = 3, cooldown = 8, statInterpolation = { 3, }, },
	},
}
skills["FireElementalFlameRedSummoned"] = {
	name = "Immolate",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.2546999454498,
	incrementalEffectiveness = 0.044599998742342,
	description = "주변의 적들에게 불줄기를 뿜어내는 토템을 소환합니다.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Damage] = true, [SkillType.Trappable] = true, [SkillType.Mineable] = true, [SkillType.SummonsTotem] = true, [SkillType.Fire] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	skillTotemId = 8,
	castTime = 0.25,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	constantStats = {
		{ "active_skill_cast_speed_+%_final", -89 },
		{ "spell_maximum_action_distance_+%", -77 },
		{ "monster_penalty_against_minions_damage_+%_final_vs_player_minions", -25 },
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_is_projectile",
		"always_pierce",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 0.8, critChance = 5, levelRequirement = 3, statInterpolation = { 3, 3, }, },
	},
}
skills["FireElementalMortarSummoned"] = {
	name = "Magma Ball",
	hidden = true,
	color = 4,
	baseEffectiveness = 3.8238000869751,
	incrementalEffectiveness = 0.034600000828505,
	description = "일반적인 몬스터 박격포 스킬입니다. 몬스터 투사체와 같지만 충격 효과를 가집니다.",
	skillTypes = { [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	constantStats = {
		{ "projectile_spread_radius", 15 },
		{ "spell_maximum_action_distance_+%", -33 },
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"is_area_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, critChance = 5, cooldown = 6, damageEffectiveness = 2, storedUses = 3, levelRequirement = 34, statInterpolation = { 3, 3, }, },
	},
}
skills["FireElementalConeSummoned"] = {
	name = "Flame Wave",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.8845000267029,
	incrementalEffectiveness = 0.03999999910593,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, [SkillType.Fire] = true, [SkillType.AreaSpell] = true, [SkillType.Cooldown] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.935,
	baseFlags = {
		spell = true,
		area = true,
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"is_area_damage",
	},
	levels = {
		[1] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 34, statInterpolation = { 3, 3, }, },
		[2] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 36, statInterpolation = { 3, 3, }, },
		[3] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 38, statInterpolation = { 3, 3, }, },
		[4] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 40, statInterpolation = { 3, 3, }, },
		[5] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 42, statInterpolation = { 3, 3, }, },
		[6] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 44, statInterpolation = { 3, 3, }, },
		[7] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 46, statInterpolation = { 3, 3, }, },
		[8] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 48, statInterpolation = { 3, 3, }, },
		[9] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 50, statInterpolation = { 3, 3, }, },
		[10] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 52, statInterpolation = { 3, 3, }, },
		[11] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 54, statInterpolation = { 3, 3, }, },
		[12] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 56, statInterpolation = { 3, 3, }, },
		[13] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 58, statInterpolation = { 3, 3, }, },
		[14] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 60, statInterpolation = { 3, 3, }, },
		[15] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 62, statInterpolation = { 3, 3, }, },
		[16] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 64, statInterpolation = { 3, 3, }, },
		[17] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 66, statInterpolation = { 3, 3, }, },
		[18] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 68, statInterpolation = { 3, 3, }, },
		[19] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 69, statInterpolation = { 3, 3, }, },
		[20] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 70, statInterpolation = { 3, 3, }, },
		[21] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 72, statInterpolation = { 3, 3, }, },
		[22] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 74, statInterpolation = { 3, 3, }, },
		[23] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 76, statInterpolation = { 3, 3, }, },
		[24] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 78, statInterpolation = { 3, 3, }, },
		[25] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 80, statInterpolation = { 3, 3, }, },
		[26] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 82, statInterpolation = { 3, 3, }, },
		[27] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 84, statInterpolation = { 3, 3, }, },
		[28] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 86, statInterpolation = { 3, 3, }, },
		[29] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 88, statInterpolation = { 3, 3, }, },
		[30] = { 0.80000001192093, 1.25, critChance = 5, cooldown = 2, damageEffectiveness = 2, storedUses = 1, levelRequirement = 90, statInterpolation = { 3, 3, }, },
	},
}
skills["IceElementalIceCyclone"] = {
	name = "Cyclone",
	hidden = true,
	color = 2,
	baseEffectiveness = 0.85000002384186,
	description = "주변 적들에게 피해를 준 뒤 목표 지점으로 이동하는 동안 연속 회전 공격을 합니다. 무자비 또는 연속타격의 보조는 받을 수 없습니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.Movement] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
		movement = true,
	},
	baseMods = {
		skill("dpsMultiplier", 2),
	},
	constantStats = {
		{ "cyclone_movement_speed_+%_final", 75 },
		{ "cyclone_extra_distance", 40 },
		{ "base_skill_effect_duration", 4000 },
	},
	stats = {
		"is_area_damage",
		"cyclone_places_ground_ice",
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 1, cooldown = 6, },
	},
}
skills["IceElementalSpearSummoned"] = {
	name = "Ice Spear",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.2813000679016,
	incrementalEffectiveness = 0.034600000828505,
	skillTypes = { [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Spell] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Damage] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_reverse_point_blank_damage_-%_at_minimum_range", 25 },
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 1.5, storedUses = 1, cooldown = 4, levelRequirement = 3, statInterpolation = { 3, 3, }, },
	},
}
skills["LightningGolemArcSummoned"] = {
	name = "Storm Orb",
	hidden = true,
	color = 3,
	baseEffectiveness = 0.78420001268387,
	incrementalEffectiveness = 0.028500000014901,
	skillTypes = { [SkillType.Duration] = true, [SkillType.Lightning] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.ProjectileSpeed] = true, [SkillType.Spell] = true, [SkillType.Triggerable] = true, [SkillType.Damage] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		spell = true,
		projectile = true,
		duration = true,
	},
	constantStats = {
		{ "base_skill_effect_duration", 8000 },
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
	},
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, critChance = 6, cooldown = 8, damageEffectiveness = 0.6, storedUses = 2, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["MonsterProjectileSpellLightningGolemSummoned"] = {
	name = "Lightning Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 3.2934999465942,
	incrementalEffectiveness = 0.036100000143051,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, [SkillType.Damage] = true, [SkillType.Multicastable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_projectile_variation", 11 },
		{ "active_skill_cast_speed_+%_final", -15 },
		{ "spell_maximum_action_distance_+%", -40 },
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, damageEffectiveness = 2.5, critChance = 6, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["LightningGolemWrath"] = {
	name = "Wrath",
	hidden = true,
	color = 3,
	baseEffectiveness = 0.16249999403954,
	incrementalEffectiveness = 0.019999999552965,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Buff] = true, [SkillType.Aura] = true, [SkillType.Lightning] = true, [SkillType.Duration] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	statMap = {
		["attack_minimum_added_lightning_damage"] = {
			mod("LightningMin", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["attack_maximum_added_lightning_damage"] = {
			mod("LightningMax", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_minimum_added_lightning_damage"] = {
			mod("LightningMin", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_maximum_added_lightning_damage"] = {
			mod("LightningMax", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
	},
	baseFlags = {
		spell = true,
		aura = true,
		area = true,
		duration = true,
	},
	constantStats = {
		{ "base_skill_effect_duration", 4000 },
	},
	stats = {
		"attack_minimum_added_lightning_damage",
		"attack_maximum_added_lightning_damage",
		"spell_minimum_added_lightning_damage",
		"spell_maximum_added_lightning_damage",
		"base_deal_no_damage",
	},
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, 0.11999999731779, 1.0800000429153, storedUses = 1, levelRequirement = 1, cooldown = 12, statInterpolation = { 3, 3, 3, 3, }, },
	},
}
skills["SpectralSkullShieldCharge"] = {
	name = "Charge",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "상대에게 돌진하여 방패로 후려침과 동시에 적을 밀어내고 기절시킵니다. 해당 경로에 있는 적들은 옆으로 밀려납니다. 피해와 기절 효과는 이동한 거리에 비례합니다. 연속타격의 보조는 받을 수 없습니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		movement = true,
	},
	constantStats = {
		{ "shield_charge_stun_duration_+%_maximum", 200 },
		{ "base_movement_velocity_+%", 500 },
		{ "shield_charge_damage_+%_maximum", 300 },
		{ "active_skill_damage_+%_final", -50 },
	},
	stats = {
		"ignores_proximity_shield",
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 1, cooldown = 5, },
	},
}
skills["RagingSpiritMeleeAttack"] = {
	name = "기본 공격",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "강력한 일격으로 적들을 쓰러트립니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	stats = {
		"active_skill_damage_+%_final",
	},
	levels = {
		[1] = { 76, levelRequirement = 4, statInterpolation = { 1, }, },
		[2] = { 71, levelRequirement = 6, statInterpolation = { 1, }, },
		[3] = { 66, levelRequirement = 9, statInterpolation = { 1, }, },
		[4] = { 61, levelRequirement = 12, statInterpolation = { 1, }, },
		[5] = { 56, levelRequirement = 15, statInterpolation = { 1, }, },
		[6] = { 52, levelRequirement = 19, statInterpolation = { 1, }, },
		[7] = { 47, levelRequirement = 23, statInterpolation = { 1, }, },
		[8] = { 42, levelRequirement = 28, statInterpolation = { 1, }, },
		[9] = { 37, levelRequirement = 33, statInterpolation = { 1, }, },
		[10] = { 32, levelRequirement = 39, statInterpolation = { 1, }, },
		[11] = { 28, levelRequirement = 43, statInterpolation = { 1, }, },
		[12] = { 23, levelRequirement = 46, statInterpolation = { 1, }, },
		[13] = { 18, levelRequirement = 49, statInterpolation = { 1, }, },
		[14] = { 12, levelRequirement = 52, statInterpolation = { 1, }, },
		[15] = { 10, levelRequirement = 55, statInterpolation = { 1, }, },
		[16] = { 7, levelRequirement = 58, statInterpolation = { 1, }, },
		[17] = { 5, levelRequirement = 61, statInterpolation = { 1, }, },
		[18] = { 2, levelRequirement = 64, statInterpolation = { 1, }, },
		[19] = { 0, levelRequirement = 66, statInterpolation = { 1, }, },
		[20] = { -2, levelRequirement = 68, statInterpolation = { 1, }, },
		[21] = { -4, levelRequirement = 70, statInterpolation = { 1, }, },
		[22] = { -7, levelRequirement = 72, statInterpolation = { 1, }, },
		[23] = { -10, levelRequirement = 74, statInterpolation = { 1, }, },
	},
}
skills["SkeletonMinionProjectileCold"] = {
	name = "Cold Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 2.1579999923706,
	incrementalEffectiveness = 0.040899999439716,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Multicastable] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.2,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, critChance = 5, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["SkeletonMinionProjectileFire"] = {
	name = "Fire Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 2.1579999923706,
	incrementalEffectiveness = 0.040899999439716,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Multicastable] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.2,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, critChance = 5, levelRequirement = 12, statInterpolation = { 3, 3, }, },
	},
}
skills["SkeletonMinionProjectileLightning"] = {
	name = "Lightning Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 2.1579999923706,
	incrementalEffectiveness = 0.040899999439716,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Multicastable] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.2,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.5, 1.5, critChance = 5, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["RockGolemSlam"] = {
	name = "Slam",
	hidden = true,
	color = 1,
	baseEffectiveness = 0,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, [SkillType.Melee] = true, [SkillType.Multistrikeable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "active_skill_attack_speed_+%_final", -20 },
		{ "chance_to_taunt_on_hit_%", 33 },
		{ "active_skill_area_of_effect_radius_+%_final", 200 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { baseMultiplier = 2, cooldown = 4, damageEffectiveness = 2, storedUses = 1, levelRequirement = 1, },
	},
}
skills["RockGolemMinionWhirlingBlades"] = {
	name = "Roll",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "나선형으로 돌진하여 무기 피해를 줍니다. 단검과 클로 한손 검으로만 사용할 수 있습니다. 연속타격의 보조는 받을 수 없습니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.43,
	baseFlags = {
		attack = true,
		melee = true,
		movement = true,
	},
	constantStats = {
		{ "skill_sound_variation", 1 },
		{ "active_skill_attack_speed_+%_final", -25 },
		{ "monster_flurry", 1 },
	},
	stats = {
		"cast_time_overrides_attack_duration",
		"ignores_proximity_shield",
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 1, cooldown = 6, },
	},
}
skills["ZombieSlam"] = {
	name = "Slam",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("radius", 18),
	},
	constantStats = {
		{ "active_skill_area_of_effect_radius_+%_final", 25 },
	},
	stats = {
		"active_skill_attack_speed_+%_final",
		"active_skill_damage_+%_final",
		"is_area_damage",
		"global_always_hit",
	},
	levels = {
		[1] = { -30, -20, storedUses = 1, levelRequirement = 1, cooldown = 6, statInterpolation = { 1, 1, }, },
		[2] = { -28, -10, storedUses = 1, levelRequirement = 12, cooldown = 6, statInterpolation = { 1, 1, }, },
		[3] = { -26, 0, storedUses = 1, levelRequirement = 20, cooldown = 6, statInterpolation = { 1, 1, }, },
		[4] = { -24, 10, storedUses = 1, levelRequirement = 33, cooldown = 6, statInterpolation = { 1, 1, }, },
		[5] = { -22, 15, storedUses = 1, levelRequirement = 45, cooldown = 6, statInterpolation = { 1, 1, }, },
	},
}
skills["SummonedSpiderViperStrike"] = {
	name = "맹독 타격",
	hidden = true,
	color = 4,
	baseEffectiveness = 0.64999997615814,
	incrementalEffectiveness = 0.025499999523163,
	description = "적을 명중시키면 물리 피해의 일부가 카오스 피해로 전환되고 중독을 유발합니다. 중독은 스킬 지속시간 관련 속성 부여의 영향을 받습니다. 쌍수를 사용할 경우 양쪽 무기 모두로 타격합니다. 클로나 단검, 검이 필요합니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Duration] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.DamageOverTime] = true, [SkillType.Chaos] = true, },
	weaponTypes = {
		["Claw"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "debuff_skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	constantStats = {
		{ "base_chance_to_poison_on_hit_%", 100 },
		{ "base_skill_effect_duration", 4000 },
	},
	stats = {
		"poison_duration_is_skill_duration",
		"visual_hit_effect_chaos_is_green",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["DancingDervishCycloneChannelled"] = {
	name = "회오리바람",
	hidden = true,
	color = 4,
	description = "이 스킬에 집중을 유지하면, 회전하는 동안 목표 지점으로 이동하면서 주변 지역의 적들을 지속적으로 공격하고 단계를 형성합니다. 스킬에 집중을 유지하는 동안에는 밀려나지 않습니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.Movement] = true, [SkillType.Channel] = true, [SkillType.Physical] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
	},
	baseMods = {
		skill("radiusIsWeaponRange", true),
	},
	constantStats = {
		{ "cyclone_gain_stage_every_x_ms_while_channelling", 170 },
		{ "cyclone_melee_weapon_range_+_per_stage", 1 },
		{ "cyclone_stage_decay_time_ms", 330 },
		{ "cyclone_max_number_of_stages", 6 },
		{ "cyclone_area_of_effect_+%_per_additional_melee_range", 8 },
	},
	stats = {
		"is_area_damage",
		"skill_can_add_multiple_charges_per_action",
	},
	levels = {
		[1] = { damageEffectiveness = 0.65, attackSpeedMultiplier = 200, baseMultiplier = 0.65, levelRequirement = 0, },
	},
}
skills["SummonPhantasmFadingProjectile"] = {
	name = "Physical Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.0221999883652,
	incrementalEffectiveness = 0.048500001430511,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.Damage] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.17,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"base_is_projectile",
		"always_pierce",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 1.5, critChance = 5, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["HeraldOfAgonyMinionMortar"] = {
	name = "Mortar",
	hidden = true,
	color = 4,
	description = "일반적인 몬스터 박격포 스킬입니다. 몬스터 투사체와 같지만 충격 효과를 가집니다.",
	skillTypes = { [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Attack] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 2,
	baseFlags = {
		attack = true,
		projectile = true,
		area = true,
	},
	constantStats = {
		{ "projectile_spread_radius", 20 },
		{ "projectile_minimum_range", 10 },
		{ "number_of_additional_projectiles", 5 },
		{ "active_skill_attack_speed_+%_final", -35 },
		{ "main_hand_base_maximum_attack_distance", 50 },
		{ "active_skill_area_of_effect_radius_+%_final", 20 },
	},
	stats = {
		"is_area_damage",
		"base_is_projectile",
		"distribute_additional_projectiles_over_contact_points",
		"visual_hit_effect_chaos_is_green",
	},
	levels = {
		[1] = { baseMultiplier = 0.4, cooldown = 7.5, damageEffectiveness = 0.4, storedUses = 1, levelRequirement = 1, },
	},
}
skills["HeraldOfAgonyMinionTailSpike"] = {
	name = "Tail Spike",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Damage] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.3,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_projectile_variation", 39 },
		{ "number_of_additional_projectiles", 4 },
	},
	stats = {
		"base_is_projectile",
		"visual_hit_effect_chaos_is_green",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["HeraldOfAgonyMinionCleave"] = {
	name = "Cleave",
	hidden = true,
	color = 1,
	description = "무기(쌍수일 경우 2개 모두)를 크게 휘둘러 범위 내 몬스터들에게 피해를 줍니다. 도끼와 검으로만 사용할 수 있습니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.ThresholdJewelArea] = true, [SkillType.Physical] = true, },
	weaponTypes = {
		["Two Handed Axe"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Two Handed Sword"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "active_skill_area_of_effect_radius_+%_final", 30 },
	},
	stats = {
		"is_area_damage",
		"visual_hit_effect_chaos_is_green",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["HeraldOfLightMinionSlam"] = {
	name = "Slam",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "active_skill_attack_speed_+%_final", -33 },
		{ "active_skill_area_of_effect_radius_+%_final", 100 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["SentinelHolySlam"] = {
	name = "Crusade Slam",
	hidden = true,
	color = 1,
	baseEffectiveness = 0,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "active_skill_attack_speed_+%_final", -33 },
		{ "active_skill_area_of_effect_radius_+%_final", 100 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { baseMultiplier = 2, cooldown = 5, damageEffectiveness = 2, storedUses = 1, levelRequirement = 0, },
	},
}
skills["RelicTriggeredNova"] = {
	name = "Nova",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.1052000522614,
	incrementalEffectiveness = 0.057900000363588,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.InbuiltTrigger] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	constantStats = {
		{ "holy_relic_trigger_on_parent_attack_%", 100 },
		{ "base_skill_effect_duration", 4000 },
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"active_skill_area_of_effect_radius_+%_final",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, -24, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 4, statInterpolation = { 3, 3, 1, }, },
		[2] = { 0.80000001192093, 1.2000000476837, -23, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 6, statInterpolation = { 3, 3, 1, }, },
		[3] = { 0.80000001192093, 1.2000000476837, -22, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 9, statInterpolation = { 3, 3, 1, }, },
		[4] = { 0.80000001192093, 1.2000000476837, -20, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 12, statInterpolation = { 3, 3, 1, }, },
		[5] = { 0.80000001192093, 1.2000000476837, -19, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 16, statInterpolation = { 3, 3, 1, }, },
		[6] = { 0.80000001192093, 1.2000000476837, -18, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 20, statInterpolation = { 3, 3, 1, }, },
		[7] = { 0.80000001192093, 1.2000000476837, -17, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 24, statInterpolation = { 3, 3, 1, }, },
		[8] = { 0.80000001192093, 1.2000000476837, -15, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 28, statInterpolation = { 3, 3, 1, }, },
		[9] = { 0.80000001192093, 1.2000000476837, -14, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 32, statInterpolation = { 3, 3, 1, }, },
		[10] = { 0.80000001192093, 1.2000000476837, -13, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 36, statInterpolation = { 3, 3, 1, }, },
		[11] = { 0.80000001192093, 1.2000000476837, -12, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 40, statInterpolation = { 3, 3, 1, }, },
		[12] = { 0.80000001192093, 1.2000000476837, -10, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 44, statInterpolation = { 3, 3, 1, }, },
		[13] = { 0.80000001192093, 1.2000000476837, -9, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 48, statInterpolation = { 3, 3, 1, }, },
		[14] = { 0.80000001192093, 1.2000000476837, -8, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 52, statInterpolation = { 3, 3, 1, }, },
		[15] = { 0.80000001192093, 1.2000000476837, -7, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 55, statInterpolation = { 3, 3, 1, }, },
		[16] = { 0.80000001192093, 1.2000000476837, -5, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 58, statInterpolation = { 3, 3, 1, }, },
		[17] = { 0.80000001192093, 1.2000000476837, -4, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 61, statInterpolation = { 3, 3, 1, }, },
		[18] = { 0.80000001192093, 1.2000000476837, -3, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 64, statInterpolation = { 3, 3, 1, }, },
		[19] = { 0.80000001192093, 1.2000000476837, -2, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 67, statInterpolation = { 3, 3, 1, }, },
		[20] = { 0.80000001192093, 1.2000000476837, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 70, statInterpolation = { 3, 3, }, },
		[21] = { 0.80000001192093, 1.2000000476837, 1, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 72, statInterpolation = { 3, 3, 1, }, },
		[22] = { 0.80000001192093, 1.2000000476837, 3, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 74, statInterpolation = { 3, 3, 1, }, },
		[23] = { 0.80000001192093, 1.2000000476837, 4, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 76, statInterpolation = { 3, 3, 1, }, },
		[24] = { 0.80000001192093, 1.2000000476837, 6, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 78, statInterpolation = { 3, 3, 1, }, },
		[25] = { 0.80000001192093, 1.2000000476837, 7, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 80, statInterpolation = { 3, 3, 1, }, },
		[26] = { 0.80000001192093, 1.2000000476837, 9, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 82, statInterpolation = { 3, 3, 1, }, },
		[27] = { 0.80000001192093, 1.2000000476837, 10, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 84, statInterpolation = { 3, 3, 1, }, },
		[28] = { 0.80000001192093, 1.2000000476837, 12, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 86, statInterpolation = { 3, 3, 1, }, },
		[29] = { 0.80000001192093, 1.2000000476837, 13, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 88, statInterpolation = { 3, 3, 1, }, },
		[30] = { 0.80000001192093, 1.2000000476837, 15, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 90, statInterpolation = { 3, 3, 1, }, },
		[31] = { 0.80000001192093, 1.2000000476837, 16, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 91, statInterpolation = { 3, 3, 1, }, },
		[32] = { 0.80000001192093, 1.2000000476837, 18, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 92, statInterpolation = { 3, 3, 1, }, },
		[33] = { 0.80000001192093, 1.2000000476837, 19, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 93, statInterpolation = { 3, 3, 1, }, },
		[34] = { 0.80000001192093, 1.2000000476837, 21, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 94, statInterpolation = { 3, 3, 1, }, },
		[35] = { 0.80000001192093, 1.2000000476837, 22, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 95, statInterpolation = { 3, 3, 1, }, },
		[36] = { 0.80000001192093, 1.2000000476837, 24, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 96, statInterpolation = { 3, 3, 1, }, },
		[37] = { 0.80000001192093, 1.2000000476837, 25, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 97, statInterpolation = { 3, 3, 1, }, },
		[38] = { 0.80000001192093, 1.2000000476837, 27, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 98, statInterpolation = { 3, 3, 1, }, },
		[39] = { 0.80000001192093, 1.2000000476837, 28, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 99, statInterpolation = { 3, 3, 1, }, },
		[40] = { 0.80000001192093, 1.2000000476837, 30, critChance = 5, cooldown = 0.3, damageEffectiveness = 2.5, storedUses = 1, levelRequirement = 100, statInterpolation = { 3, 3, 1, }, },
	},
}
skills["DominatingBlowMinionCharge"] = {
	name = "방패 돌진",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "대상 지점으로 돌진하여 경로상에 있는 적들을 밀어내고 피해를 주며 대상 지점에 도착 시 범위 피해를 줍니다. 또한 이동거리가 멀수록 적들에게 주는 피해가 증가하며 기절시킬 확률이 높아집니다. 연속타격의 보조는 받을 수 없습니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RequiresShield] = true, [SkillType.Melee] = true, [SkillType.Area] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	constantStats = {
		{ "shield_charge_scaling_stun_threshold_reduction_+%_at_maximum_range", 25 },
		{ "base_movement_velocity_+%", 400 },
		{ "shield_charge_damage_+%_maximum", 30 },
		{ "active_skill_area_of_effect_radius_+%_final", -40 },
	},
	stats = {
		"ignores_proximity_shield",
		"global_cannot_crit",
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 1, cooldown = 4, },
	},
}
skills["AbsolutionMinion"] = {
	name = "면죄",
	hidden = true,
	color = 1,
	baseEffectiveness = 1.9819999933243,
	incrementalEffectiveness = 0.045299999415874,
	description = "지역에 있는 적에게 피해를 주고 짧은 시간 동안 디버프를 적용합니다. 디버프의 영향을 받는 동안 비-고유 적이 죽으면, 해당 적의 시신을 소모하여 더 긴 2차 지속시간 동안 면죄의 파수꾼 1명이 소환됩니다. 이미 소환된 파수꾼의 수가 최대치라면 기존 파수꾼 1명의 지속시간과 생명력이 초기화됩니다.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.Duration] = true, [SkillType.Physical] = true, [SkillType.Lightning] = true, [SkillType.MinionsCanExplode] = true, [SkillType.CreatesMinion] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Multicastable] = true, [SkillType.Cascadable] = true, [SkillType.Triggerable] = true, [SkillType.Totemable] = true, [SkillType.Trappable] = true, [SkillType.Mineable] = true, [SkillType.CanRapidFire] = true, },
	statDescriptionScope = "minion_spell_damage_skill_stat_descriptions",
	castTime = 0.75,
	baseFlags = {
		area = true,
		spell = true,
		duration = true,
	},
	constantStats = {
		{ "spell_maximum_action_distance_+%", -50 },
		{ "active_skill_area_of_effect_radius_+%_final", -25 },
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"is_area_damage",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 1.8, critChance = 6, levelRequirement = 12, statInterpolation = { 3, 3, }, },
	},
}
skills["AbsolutionMinionEmpowered"] = {
	name = "면죄",
	hidden = true,
	color = 1,
	baseEffectiveness = 1.4865000247955,
	incrementalEffectiveness = 0.045299999415874,
	description = "지역에 있는 적에게 피해를 주고 짧은 시간 동안 디버프를 적용합니다. 디버프의 영향을 받는 동안 비-고유 적이 죽으면, 해당 적의 시신을 소모하여 더 긴 2차 지속시간 동안 면죄의 파수꾼 1명이 소환됩니다. 이미 소환된 파수꾼의 수가 최대치라면 기존 파수꾼 1명의 지속시간과 생명력이 초기화됩니다.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.Duration] = true, [SkillType.Physical] = true, [SkillType.Lightning] = true, [SkillType.MinionsCanExplode] = true, [SkillType.CreatesMinion] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Multicastable] = true, [SkillType.Cascadable] = true, [SkillType.Triggerable] = true, [SkillType.Totemable] = true, [SkillType.Trappable] = true, [SkillType.Mineable] = true, [SkillType.CanRapidFire] = true, },
	statDescriptionScope = "minion_spell_damage_skill_stat_descriptions",
	castTime = 0.75,
	baseFlags = {
		area = true,
		spell = true,
		duration = true,
	},
	constantStats = {
		{ "spell_maximum_action_distance_+%", -50 },
		{ "absolution_blast_shockwave_every_x_beams", 1 },
		{ "active_skill_area_of_effect_radius_+%_final", -25 },
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"is_area_damage",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, critChance = 6, cooldown = 6, damageEffectiveness = 1.3, storedUses = 1, levelRequirement = 0, statInterpolation = { 3, 3, }, },
	},
}
skills["SummonedRhoaShieldCharge"] = {
	name = "방패 돌진",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "대상 지점으로 돌진하여 경로상에 있는 적들을 밀어내고 피해를 주며 대상 지점에 도착 시 범위 피해를 줍니다. 또한 이동거리가 멀수록 적들에게 주는 피해가 증가하며 기절시킬 확률이 높아집니다. 연속타격의 보조는 받을 수 없습니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RequiresShield] = true, [SkillType.Melee] = true, [SkillType.Area] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "shield_charge_scaling_stun_threshold_reduction_+%_at_maximum_range", 50 },
		{ "base_movement_velocity_+%", 100 },
		{ "shield_charge_damage_+%_maximum", 10 },
		{ "attack_speed_+%", 20 },
		{ "physical_damage_%_to_add_as_lightning", 15 },
	},
	stats = {
		"ignores_proximity_shield",
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 1, cooldown = 3, },
	},
}
skills["SummonedSnakeProjectile"] = {
	name = "Chaos Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.8700000047684,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Damage] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_projectile_variation", 1 },
	},
	stats = {
		"base_is_projectile",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["DropBearSummonedGroundSlam"] = {
	name = "대지 강타",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "지팡이나 철퇴, 셉터로 전방의 바닥을 후려치면 앞쪽으로 파도를 일으키며 뻗어 나가 적들에게 피해를 주고 증가된 확률로 기절시킵니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.Slam] = true, [SkillType.Totemable] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Two Handed Mace"] = true,
		["Staff"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 1, cooldown = 3, },
	},
}
skills["DropBearSummonedRallyingCry"] = {
	name = "집결의 함성",
	hidden = true,
	color = 1,
	description = "함성을 질러, 주변에 적이 있을 경우 시전자 및 주변 동료들의 피해와 마나 재생을 증가시킵니다. 피해 증가는 주변의 적 숫자에 비례합니다. 주변의 모든 적이 시전자를 공격하도록 도발하는 효과가 있습니다. 다른 함성 스킬과 재사용 대기시간을 공유합니다.",
	skillTypes = { [SkillType.Buff] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.Warcry] = true, [SkillType.Cooldown] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.25,
	statMap = {
		["damage_+%"] = {
			mod("Damage", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		},
	},
	baseFlags = {
		warcry = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("buffAllies", true),
	},
	constantStats = {
		{ "damage_+%", 25 },
		{ "base_skill_effect_duration", 4000 },
		{ "base_mana_regeneration_rate_per_minute", 888 },
		{ "active_skill_area_of_effect_radius_+%_final", -25 },
	},
	stats = {
		"base_deal_no_damage",
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 1, cooldown = 5, },
	},
}
skills["BoneGolemMultiAttack"] = {
	name = "Combo Attack",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	statMap = {
		["bone_golem_attack_speed_+%_final_after_third_combo_index"] = {
			mod("Speed", "MORE", nil, 0, KeywordFlag.Attack),
			div = 1.5,
		},
		["bone_golem_damage_+%_final_after_third_combo_index"] = {
			mod("Damage", "MORE", nil),
			div = 1.5,
		},
	},
	baseFlags = {
		attack = true,
		melee = true,
	},
	constantStats = {
		{ "bone_golem_attack_speed_+%_final_after_third_combo_index", 200 },
		{ "bone_golem_damage_+%_final_after_third_combo_index", 20 },
	},
	stats = {
	},
	levels = {
		[1] = { damageEffectiveness = 1.35, baseMultiplier = 1.35, levelRequirement = 1, },
	},
}
skills["BoneGolemCascade"] = {
	name = "Cascade",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	constantStats = {
		{ "upheaval_number_of_spikes", 4 },
		{ "active_skill_base_radius_+", 1 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { attackSpeedMultiplier = -10, cooldown = 6, damageEffectiveness = 0.65, storedUses = 1, baseMultiplier = 0.65, levelRequirement = 1, },
	},
}
skills["BoneGolemLeapSlam"] = {
	name = "도약 강타",
	hidden = true,
	color = 4,
	description = "원하는 지점으로 도약 후 착지하면서 무기로 적들에게 피해를 주고 밀쳐 냅니다. 착지 지점의 적은 바깥으로 밀려납니다. 도끼나 철퇴, 셉터, 검, 지팡이가 필요합니다. 연속타격의 보조는 받을 수 없습니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, [SkillType.Slam] = true, [SkillType.Totemable] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	constantStats = {
		{ "active_skill_area_of_effect_radius_+%_final", 30 },
	},
	stats = {
		"is_area_damage",
		"disable_attack_repeats",
	},
	levels = {
		[1] = { attackSpeedMultiplier = -44, cooldown = 4, damageEffectiveness = 1.8, storedUses = 1, baseMultiplier = 1.8, levelRequirement = 1, },
	},
}
skills["SkitterbotWait"] = {
	name = "Skitterbot Wait",
	hidden = true,
	color = 4,
	skillTypes = { },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		duration = true,
	},
	constantStats = {
		{ "base_skill_effect_duration", 200 },
	},
	stats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
	},
}
skills["MinionInstability"] = {
	name = "Minion Instability",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		fire = true,
	},
	skillTypes = { [SkillType.Damage] = true, [SkillType.Area] = true },
	baseMods = {
		skill("FireMin", 1, { type = "PerStat", stat = "Life", div = 1/.33 }),
		skill("FireMax", 1, { type = "PerStat", stat = "Life", div = 1/.33 }),
		skill("showAverage", true),
		skill("radius", 22),
	},
	stats = {
	},
	levelMods = {
	},
	levels = {
		[1] = { cost = { } },
	},
}
skills["SiegebreakerCausticGround"] = {
	name = "Caustic Ground",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		chaos = true,
	},
	skillTypes = { },
	baseMods = {
		skill("ChaosDot", 1, { type = "PerStat", stat = "Life", div = 5 }),
		skill("dotIsArea", true),
		flag("dotIsCausticGround"),
	},
	qualityStats = {
	},
	stats = {
	},
	levels = {
		[1] = { cost = { } },
	},
}
skills["ReplicaSiegebreakerBurningGround"] = {
	name = "Burning Ground",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		fire = true,
	},
	skillTypes = { },
	baseMods = {
		skill("FireDot", 1, { type = "PerStat", stat = "Life", div = 5 }),
		skill("dotIsArea", true),
		flag("dotIsBurningGround"),
	},
	qualityStats = {
	},
	stats = {
	},
	levels = {
		[1] = { cost = { } },
	},
}
skills["InfernalLegion"] = {
	name = "Infernal Legion",
	hidden = true,
	color = 4,
	baseFlags = {
		spell = true,
		area = true,
	},
	skillTypes = { },
	baseMods = {
		skill("FireDot", 1, { type = "Multiplier", var = "InfernalLegionBaseDamage" }),
		skill("dotIsArea", true),
	},
	qualityStats = {
	},
	stats = {
	},
	levels = {
		[1] = { cost = { } },
	},
}

skills["MeleeAtAnimationSpeedUnique"] = {
	name = "Default Attack",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "강력한 일격으로 적들을 쓰러트립니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		projectile = true,
	},
	stats = {
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"action_attack_or_cast_time_uses_animation_length",
		"projectile_uses_contact_position",
		"use_scaled_contact_offset",
	},
	levels = {
		[1] = { attackSpeedMultiplier = -25, levelRequirement = 1, },
	},
}
skills["SummonedReaperMelee"] = {
	name = "Default Attack",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "강력한 일격으로 적들을 쓰러트립니다.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		projectile = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"action_attack_or_cast_time_uses_animation_length",
	},
	levels = {
		[1] = { 1, damageEffectiveness = 0.5, baseMultiplier = 0.5, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, damageEffectiveness = 0.5, baseMultiplier = 0.5, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["SummonedReaperUltimate"] = {
	name = "Ultimate",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Movement] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 2,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, damageEffectiveness = 1.5, baseMultiplier = 1.5, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, damageEffectiveness = 1.65, baseMultiplier = 1.65, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["GASummonReaperUltimateLeftSlash"] = {
	name = "Ultimate Slash",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, damageEffectiveness = 1.5, baseMultiplier = 1.5, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, damageEffectiveness = 1.5, baseMultiplier = 1.5, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["GASummonReaperComboWhirl"] = {
	name = "Whirl",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, damageEffectiveness = 0.5, baseMultiplier = 0.5, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, damageEffectiveness = 0.5, baseMultiplier = 0.5, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["GASummonReaperComboLeftSlash"] = {
	name = "Combo Slash",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["ReaperConsumeMinionForBuff"] = {
	name = "Consume",
	hidden = true,
	color = 4,
	skillTypes = { },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
	},
	baseMods = {
		mod("MinionModifier", "LIST", { mod = mod("Damage", "INC", 40) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper" }, { type = "GlobalEffect", effectType = "Buff" }),
		mod("MinionModifier", "LIST", { mod = mod("Speed", "INC", 20) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper" }, { type = "GlobalEffect", effectType = "Buff" }),
		mod("MinionModifier", "LIST", { mod = mod("MovementSpeed", "INC", 20) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper" }, { type = "GlobalEffect", effectType = "Buff" }),
		skill("buffAllies", true),
	},
	constantStats = {
		{ "base_skill_effect_duration", 6000 },
	},
	stats = {
	},
	levels = {
		[1] = { storedUses = 1, levelRequirement = 0, cooldown = 25, },
	},
}
skills["MPWExpeditionSummonedArbalestProjectile"] = {
	name = "Projectile Attack",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Damage] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.5,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_projectile_variation", 145 },
	},
	stats = {
		"base_is_projectile",
		"projectile_uses_contact_position",
		"use_scaled_contact_offset",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}